// @generated by generate_windowed_r0_production; do not edit.

use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};

use super::binding::WindowLaunchBinding;

/// `(native shape mask, compiled kernel mask, min blocks per SM)`, mirroring
/// `gpu_gkr_compiler::backward::WINDOWED_R0_DISPATCH`.
pub(crate) const WINDOWED_R0_DISPATCH: [(u16, u16, u32); 14] = [
    (0x001, 0x471, 4),
    (0x020, 0x4f6, 3),
    (0x1b1, 0x1b1, 3),
    (0x1b7, 0x5f7, 4),
    (0x3f7, 0x7ff, 4),
    (0x3fb, 0x3ff, 4),
    (0x460, 0xc78, 3),
    (0x470, 0x7f7, 3),
    (0x4f6, 0x4f6, 3),
    (0x9bf, 0xfff, 4),
    (0xbfb, 0xffb, 4),
    (0xbff, 0xfff, 4),
    (0xc78, 0xc7a, 3),
    (0xc7a, 0xc7a, 3),
];

/// Compiled mask a well-formed shape the map does not name falls back to.
pub(crate) const WINDOWED_R0_FALLBACK_MASK: u16 = 0xfff;

/// Threads per block every generated window kernel is compiled for.
pub(crate) const WINDOWED_R0_BLOCK_THREADS: u32 = 288;

cuda_kernel_signature_arguments_and_function!(
    pub(crate) GkrBwdR0Window3,
    desc: WindowLaunchBinding,
);

/// One generated entry point.
pub(crate) struct WindowKernelEntry {
    pub mask: u16,
    pub min_blocks: u32,
    pub symbol_name: &'static str,
    pub symbol: GkrBwdR0Window3Signature,
}

cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_1b1_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_3ff_b4_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_471_b4_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_4f6_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_5f7_b4_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_7f7_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_7ff_b4_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_c78_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_c7a_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_ffb_b4_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_fff_b4_kernel(desc: WindowLaunchBinding)
);

pub(crate) const WINDOWED_R0_KERNELS: [WindowKernelEntry; 11] = [
    WindowKernelEntry {
        mask: 0x1b1,
        min_blocks: 3,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_1b1_b3_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_1b1_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0x3ff,
        min_blocks: 4,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_3ff_b4_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_3ff_b4_kernel,
    },
    WindowKernelEntry {
        mask: 0x471,
        min_blocks: 4,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_471_b4_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_471_b4_kernel,
    },
    WindowKernelEntry {
        mask: 0x4f6,
        min_blocks: 3,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_4f6_b3_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_4f6_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0x5f7,
        min_blocks: 4,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_5f7_b4_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_5f7_b4_kernel,
    },
    WindowKernelEntry {
        mask: 0x7f7,
        min_blocks: 3,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_7f7_b3_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_7f7_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0x7ff,
        min_blocks: 4,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_7ff_b4_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_7ff_b4_kernel,
    },
    WindowKernelEntry {
        mask: 0xc78,
        min_blocks: 3,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_c78_b3_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_c78_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0xc7a,
        min_blocks: 3,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_c7a_b3_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_c7a_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0xffb,
        min_blocks: 4,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_ffb_b4_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_ffb_b4_kernel,
    },
    WindowKernelEntry {
        mask: 0xfff,
        min_blocks: 4,
        symbol_name: "ab_gkr_bwd_r0_window3_shape_fff_b4_kernel",
        symbol: ab_gkr_bwd_r0_window3_shape_fff_b4_kernel,
    },
];
