// @generated by generate_windowed_r0_production; do not edit.

use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};

use super::binding::WindowLaunchBinding;

/// `(native shape mask, compiled kernel mask, min blocks per SM)`, mirroring
/// `gpu_gkr_compiler::backward::WINDOWED_R0_DISPATCH`.
pub(crate) const WINDOWED_R0_DISPATCH: [(u16, u16, u32); 14] = [
    (0x001, 0x471, 4),
    (0x020, 0xfff, 3),
    (0x1b1, 0xfff, 3),
    (0x1b7, 0xfff, 4),
    (0x3f7, 0xfff, 4),
    (0x3fb, 0xfff, 3),
    (0x460, 0xfff, 3),
    (0x470, 0xfff, 3),
    (0x4f6, 0x4f6, 3),
    (0x9bf, 0xfff, 4),
    (0xbfb, 0xfff, 3),
    (0xbff, 0xfff, 4),
    (0xc78, 0xfff, 3),
    (0xc7a, 0xfff, 3),
];

/// Fixed universal entry for a shape absent from the dispatch map.
pub(crate) const WINDOWED_R0_FALLBACK: (u16, u32) = (0xfff, 4);

/// Threads per block every generated window kernel is compiled for.
pub(crate) const WINDOWED_R0_BLOCK_THREADS: u32 = 288;

cuda_kernel_signature_arguments_and_function!(
    pub(crate) GkrBwdR0Window3,
    desc: WindowLaunchBinding,
);

pub(crate) struct WindowKernelEntry {
    pub mask: u16,
    pub min_blocks: u32,
    pub symbol: GkrBwdR0Window3Signature,
}

cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_471_b4_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_4f6_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_fff_b3_kernel(desc: WindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_r0_window3_shape_fff_b4_kernel(desc: WindowLaunchBinding)
);

pub(crate) const WINDOWED_R0_KERNELS: [WindowKernelEntry; 4] = [
    WindowKernelEntry {
        mask: 0x471,
        min_blocks: 4,
        symbol: ab_gkr_bwd_r0_window3_shape_471_b4_kernel,
    },
    WindowKernelEntry {
        mask: 0x4f6,
        min_blocks: 3,
        symbol: ab_gkr_bwd_r0_window3_shape_4f6_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0xfff,
        min_blocks: 3,
        symbol: ab_gkr_bwd_r0_window3_shape_fff_b3_kernel,
    },
    WindowKernelEntry {
        mask: 0xfff,
        min_blocks: 4,
        symbol: ab_gkr_bwd_r0_window3_shape_fff_b4_kernel,
    },
];
