//! Authoritative generated-kernel bank for width-three main continuations.
//!
//! The seven corpus masks each have an exact executor. Every other well-formed
//! shape is routed to the `0x1f` universal executor. Launch-bound probing uses
//! the same pure renderers as committed generation, but cannot change the
//! authoritative mask domain.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use super::main_continuation_window::{
    MainContinuationWindowLoweringError, MainContinuationWindowShape,
    MAIN_CONTINUATION_WINDOW_SHAPE_DEFINED_BITS,
};

/// `(compiled shape mask, minimum blocks per SM)`, sorted by mask.
///
/// Bounds begin conservatively at one. They are updated only after the ruled
/// linked-image launch-bound sweep proves a stronger bound spill-free.
pub const MAIN_CONTINUATION_WINDOW_KERNEL_BANK: [(u16, u32); 7] = [
    (0x00, 1),
    (0x01, 1),
    (0x03, 1),
    (0x07, 1),
    (0x13, 1),
    (0x17, 1),
    (0x1f, 1),
];

/// Universal executor used for well-formed masks absent from the exact bank.
pub const MAIN_CONTINUATION_WINDOW_FALLBACK_MASK: u16 = MAIN_CONTINUATION_WINDOW_SHAPE_DEFINED_BITS;
/// Number of generated continuation-window entry points.
pub const MAIN_CONTINUATION_WINDOW_KERNEL_COUNT: usize = 7;
/// Threads per block for every continuation-window kernel.
pub const MAIN_CONTINUATION_WINDOW_BLOCK_THREADS: u32 = 288;

const EXPECTED_MASKS: [u16; MAIN_CONTINUATION_WINDOW_KERNEL_COUNT] =
    [0x00, 0x01, 0x03, 0x07, 0x13, 0x17, 0x1f];
const GENERATED_HEADER: &str =
    "// @generated by generate_main_continuation_window_production; do not edit.";
const MANIFEST_HEADER_NAME: &str = "main_continuation_window_manifest.cuh";

/// Repo-relative directory containing the generated native bank.
pub const MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR: &str =
    "gpu/gkr/native/gkr/backward/main_continuation_window/generated";
/// Repo-relative path of the generated Rust FFI registry.
pub const MAIN_CONTINUATION_WINDOW_GENERATED_REGISTRY: &str =
    "gpu/gkr/src/backward/main_continuation/generated_registry.rs";

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct CandidateBankRow {
    mask: u16,
    min_blocks: u32,
}

/// Repository root, resolved independently of the process working directory.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("resolve repository root from CARGO_MANIFEST_DIR")
        .to_path_buf()
}

/// Validate the exact mask domain and supported launch-bound candidates.
pub fn validate_main_continuation_window_kernel_bank(bank: &[(u16, u32)]) -> Result<(), String> {
    if bank.len() != MAIN_CONTINUATION_WINDOW_KERNEL_COUNT {
        return Err(format!(
            "candidate bank has {} rows, expected {MAIN_CONTINUATION_WINDOW_KERNEL_COUNT}",
            bank.len()
        ));
    }
    for (index, ((mask, min_blocks), expected_mask)) in bank.iter().zip(EXPECTED_MASKS).enumerate()
    {
        if *mask != expected_mask {
            return Err(format!(
                "candidate row {index} has mask {mask:#04x}, expected {expected_mask:#04x}"
            ));
        }
        if !(1..=4).contains(min_blocks) {
            return Err(format!(
                "candidate mask {mask:#04x} has unsupported launch bound {min_blocks}; expected 1..=4"
            ));
        }
    }
    if bank.last().map(|row| row.0) != Some(MAIN_CONTINUATION_WINDOW_FALLBACK_MASK) {
        return Err("candidate bank omits the universal fallback mask".to_owned());
    }
    Ok(())
}

/// Resolve a required shape to an exact kernel or the universal executor.
pub fn resolve_main_continuation_window_kernel(
    mask: u16,
) -> Result<(u16, u32), MainContinuationWindowLoweringError> {
    MainContinuationWindowShape::from_bits(mask)?;
    if let Some(row) = MAIN_CONTINUATION_WINDOW_KERNEL_BANK
        .iter()
        .copied()
        .find(|row| row.0 == mask)
    {
        return Ok(row);
    }
    Ok(*MAIN_CONTINUATION_WINDOW_KERNEL_BANK
        .last()
        .expect("the validated kernel bank contains the universal executor"))
}

/// Parse the launch-bound probe schema. It is exactly seven sorted rows, with
/// no unknown fields, the authoritative mask set, and bounds in `1..=4`.
pub fn parse_main_continuation_window_candidate_bank(
    json: &str,
) -> Result<Vec<(u16, u32)>, String> {
    let rows: Vec<CandidateBankRow> = serde_json::from_str(json)
        .map_err(|error| format!("invalid candidate bank JSON: {error}"))?;
    let bank: Vec<(u16, u32)> = rows
        .into_iter()
        .map(|row| (row.mask, row.min_blocks))
        .collect();
    validate_main_continuation_window_kernel_bank(&bank)?;
    Ok(bank)
}

pub fn main_continuation_window_kernel_symbol(mask: u16, min_blocks: u32) -> String {
    format!("ab_gkr_bwd_main_cont_window3_shape_{mask:02x}_b{min_blocks}_kernel")
}

pub fn main_continuation_window_translation_unit_name(mask: u16) -> String {
    format!("main_continuation_window_shape_{mask:02x}.cu")
}

/// Render all artifacts from an explicit validated bank. Both authoritative
/// generation and probe generation call this function.
pub fn main_continuation_window_generated_artifacts_for_bank(
    bank: &[(u16, u32)],
) -> Result<Vec<(String, String)>, String> {
    validate_main_continuation_window_kernel_bank(bank)?;
    let mut artifacts = vec![(
        format!("{MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR}/{MANIFEST_HEADER_NAME}"),
        render_main_continuation_window_manifest(bank),
    )];
    for &(mask, min_blocks) in bank {
        artifacts.push((
            format!(
                "{MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR}/{}",
                main_continuation_window_translation_unit_name(mask)
            ),
            render_main_continuation_window_translation_unit(mask, min_blocks),
        ));
    }
    artifacts.push((
        MAIN_CONTINUATION_WINDOW_GENERATED_REGISTRY.to_owned(),
        render_main_continuation_window_registry(bank),
    ));
    Ok(artifacts)
}

/// Render the committed authoritative artifact set.
pub fn main_continuation_window_generated_artifacts() -> Result<Vec<(String, String)>, String> {
    main_continuation_window_generated_artifacts_for_bank(&MAIN_CONTINUATION_WINDOW_KERNEL_BANK)
}

pub fn render_main_continuation_window_manifest(bank: &[(u16, u32)]) -> String {
    format!(
        "{GENERATED_HEADER}\n\
         #pragma once\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         inline constexpr unsigned BWD_MAIN_CONTINUATION_WINDOW_KERNEL_COUNT = {};\n\
         inline constexpr unsigned BWD_MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK = {:#04x};\n\
         \n\
         }} // namespace airbender::gkr::backward\n",
        bank.len(),
        MAIN_CONTINUATION_WINDOW_FALLBACK_MASK,
    )
}

pub fn render_main_continuation_window_translation_unit(mask: u16, min_blocks: u32) -> String {
    let symbol = main_continuation_window_kernel_symbol(mask, min_blocks);
    format!(
        "{GENERATED_HEADER}\n\
         #include \"../executor.cuh\"\n\
         #include \"{MANIFEST_HEADER_NAME}\"\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         AB_GKR_BWD_MAIN_CONT_WINDOW_DEFINE_KERNEL({symbol}, {mask:#04x}, {min_blocks});\n\
         \n\
         static_assert(BWD_MAIN_CONTINUATION_WINDOW_KERNEL_COUNT == {MAIN_CONTINUATION_WINDOW_KERNEL_COUNT}, \"shape_{mask:02x} continuation-window manifest drift\");\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_main_continuation_window_registry(bank: &[(u16, u32)]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\n\n");
    out.push_str(
        "use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};\n\n",
    );
    out.push_str("use super::binding::MainContinuationWindowLaunchBinding;\n\n");
    out.push_str("/// `(compiled shape mask, min blocks per SM)`, sorted by mask.\n");
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_KERNEL_BANK: [(u16, u32); {}] = [\n",
        bank.len()
    ));
    for (mask, min_blocks) in bank {
        out.push_str(&format!("    ({mask:#04x}, {min_blocks}),\n"));
    }
    out.push_str("];\n\n");
    out.push_str("/// Universal executor for well-formed masks absent from the exact bank.\n");
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_FALLBACK_MASK: u16 = {MAIN_CONTINUATION_WINDOW_FALLBACK_MASK:#04x};\n\n"
    ));
    out.push_str("/// Threads per block for every generated continuation-window kernel.\n");
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_BLOCK_THREADS: u32 = {MAIN_CONTINUATION_WINDOW_BLOCK_THREADS};\n\n"
    ));
    out.push_str("cuda_kernel_signature_arguments_and_function!(\n");
    out.push_str("    pub(crate) GkrBwdMainContinuationWindow3,\n");
    out.push_str("    desc: MainContinuationWindowLaunchBinding,\n");
    out.push_str(");\n\n");
    out.push_str("/// One generated continuation-window entry point.\n");
    out.push_str("pub(crate) struct MainContinuationWindowKernelEntry {\n");
    out.push_str("    pub mask: u16,\n");
    out.push_str("    pub min_blocks: u32,\n");
    out.push_str("    pub symbol_name: &'static str,\n");
    out.push_str("    pub symbol: GkrBwdMainContinuationWindow3Signature,\n");
    out.push_str("}\n\n");
    for &(mask, min_blocks) in bank {
        out.push_str(&format!(
            "cuda_kernel_declaration!(\n    pub(crate) {}(desc: MainContinuationWindowLaunchBinding)\n);\n",
            main_continuation_window_kernel_symbol(mask, min_blocks)
        ));
    }
    out.push('\n');
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_KERNELS: [MainContinuationWindowKernelEntry; {}] = [\n",
        bank.len()
    ));
    for &(mask, min_blocks) in bank {
        let symbol = main_continuation_window_kernel_symbol(mask, min_blocks);
        out.push_str("    MainContinuationWindowKernelEntry {\n");
        out.push_str(&format!("        mask: {mask:#04x},\n"));
        out.push_str(&format!("        min_blocks: {min_blocks},\n"));
        out.push_str(&format!("        symbol_name: \"{symbol}\",\n"));
        out.push_str(&format!("        symbol: {symbol},\n"));
        out.push_str("    },\n");
    }
    out.push_str("];\n");
    out
}

fn expected_generated_native_entries() -> Vec<String> {
    let mut expected: Vec<String> = EXPECTED_MASKS
        .into_iter()
        .map(main_continuation_window_translation_unit_name)
        .collect();
    expected.push(MANIFEST_HEADER_NAME.to_owned());
    expected.sort();
    expected
}

/// Fail if the generated native directory contains a stale or extra file.
pub fn validate_main_continuation_window_generated_tree(root: &Path) -> Result<(), String> {
    let directory = root.join(MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR);
    let mut present: Vec<String> = std::fs::read_dir(&directory)
        .map_err(|error| format!("{}: {error}", directory.display()))?
        .map(|entry| {
            entry
                .map_err(|error| error.to_string())
                .map(|entry| entry.file_name().to_string_lossy().into_owned())
        })
        .collect::<Result<_, _>>()?;
    present.sort();
    let expected = expected_generated_native_entries();
    if present != expected {
        return Err(format!(
            "generated native tree differs: present={present:?}, expected={expected:?}"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const RULED_BANK: [(u16, u32); 7] = [
        (0x00, 1),
        (0x01, 1),
        (0x03, 1),
        (0x07, 1),
        (0x13, 1),
        (0x17, 1),
        (0x1f, 1),
    ];

    #[test]
    fn cpu_main_continuation_window_manifest_matches_ruled_bank() {
        assert_eq!(MAIN_CONTINUATION_WINDOW_KERNEL_BANK, RULED_BANK);
        validate_main_continuation_window_kernel_bank(&RULED_BANK).unwrap();
        assert_eq!(MAIN_CONTINUATION_WINDOW_FALLBACK_MASK, 0x1f);
        assert_eq!(MAIN_CONTINUATION_WINDOW_KERNEL_COUNT, 7);
    }

    #[test]
    fn cpu_main_continuation_window_manifest_resolves_exact_and_universal_shapes() {
        for (mask, min_blocks) in RULED_BANK {
            assert_eq!(
                resolve_main_continuation_window_kernel(mask).unwrap(),
                (mask, min_blocks)
            );
        }
        for mask in 0..=MAIN_CONTINUATION_WINDOW_FALLBACK_MASK {
            let expected = RULED_BANK
                .iter()
                .copied()
                .find(|row| row.0 == mask)
                .unwrap_or((MAIN_CONTINUATION_WINDOW_FALLBACK_MASK, 1));
            assert_eq!(
                resolve_main_continuation_window_kernel(mask).unwrap(),
                expected
            );
        }
        assert!(resolve_main_continuation_window_kernel(0x20).is_err());
    }

    #[test]
    fn cpu_main_continuation_window_manifest_probe_schema_is_strict() {
        let valid = r#"[
            {"mask":0,"min_blocks":4},
            {"mask":1,"min_blocks":3},
            {"mask":3,"min_blocks":2},
            {"mask":7,"min_blocks":1},
            {"mask":19,"min_blocks":4},
            {"mask":23,"min_blocks":3},
            {"mask":31,"min_blocks":2}
        ]"#;
        assert_eq!(
            parse_main_continuation_window_candidate_bank(valid).unwrap(),
            vec![
                (0x00, 4),
                (0x01, 3),
                (0x03, 2),
                (0x07, 1),
                (0x13, 4),
                (0x17, 3),
                (0x1f, 2)
            ]
        );

        for invalid in [
            "[]",
            r#"[{"mask":0,"min_blocks":1,"extra":0}]"#,
            r#"[{"mask":0,"min_blocks":0},{"mask":1,"min_blocks":1},{"mask":3,"min_blocks":1},{"mask":7,"min_blocks":1},{"mask":19,"min_blocks":1},{"mask":23,"min_blocks":1},{"mask":31,"min_blocks":1}]"#,
            r#"[{"mask":0,"min_blocks":5},{"mask":1,"min_blocks":1},{"mask":3,"min_blocks":1},{"mask":7,"min_blocks":1},{"mask":19,"min_blocks":1},{"mask":23,"min_blocks":1},{"mask":31,"min_blocks":1}]"#,
            r#"[{"mask":1,"min_blocks":1},{"mask":0,"min_blocks":1},{"mask":3,"min_blocks":1},{"mask":7,"min_blocks":1},{"mask":19,"min_blocks":1},{"mask":23,"min_blocks":1},{"mask":31,"min_blocks":1}]"#,
            r#"[{"mask":0,"min_blocks":1},{"mask":1,"min_blocks":1},{"mask":3,"min_blocks":1},{"mask":7,"min_blocks":1},{"mask":19,"min_blocks":1},{"mask":23,"min_blocks":1},{"mask":30,"min_blocks":1}]"#,
        ] {
            assert!(
                parse_main_continuation_window_candidate_bank(invalid).is_err(),
                "accepted invalid probe payload: {invalid}"
            );
        }
    }

    #[test]
    fn cpu_main_continuation_window_manifest_rendering_tracks_candidate_bounds() {
        let candidate = vec![
            (0x00, 4),
            (0x01, 3),
            (0x03, 2),
            (0x07, 1),
            (0x13, 4),
            (0x17, 3),
            (0x1f, 2),
        ];
        let artifacts = main_continuation_window_generated_artifacts_for_bank(&candidate).unwrap();
        assert_eq!(artifacts.len(), MAIN_CONTINUATION_WINDOW_KERNEL_COUNT + 2);
        assert!(artifacts.iter().any(|(path, contents)| {
            path.ends_with("main_continuation_window_shape_00.cu")
                && contents.contains("ab_gkr_bwd_main_cont_window3_shape_00_b4_kernel")
        }));
        let registry = artifacts
            .iter()
            .find(|(path, _)| path == MAIN_CONTINUATION_WINDOW_GENERATED_REGISTRY)
            .unwrap();
        assert!(registry.1.contains("(0x00, 4)"));
        assert!(registry.1.contains("(0x1f, 2)"));
    }

    #[test]
    fn cpu_main_continuation_window_manifest_committed_artifacts_are_current() {
        let root = repo_root();
        for (relative, rendered) in main_continuation_window_generated_artifacts().unwrap() {
            let committed = std::fs::read_to_string(root.join(&relative))
                .unwrap_or_else(|error| panic!("{relative}: {error}"));
            assert_eq!(
                committed, rendered,
                "{relative} is stale; rerun generate_main_continuation_window_production --write"
            );
        }
    }

    #[test]
    fn cpu_main_continuation_window_manifest_generated_tree_has_no_extra_files() {
        validate_main_continuation_window_generated_tree(&repo_root()).unwrap();
    }

    #[test]
    fn cpu_main_continuation_window_manifest_extra_file_mutation_is_rejected() {
        let root = std::env::temp_dir().join(format!(
            "gpu-gkr-main-cont-generated-tree-{}",
            std::process::id()
        ));
        let generated = root.join(MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR);
        std::fs::create_dir_all(&generated).unwrap();
        for name in expected_generated_native_entries() {
            std::fs::write(generated.join(name), b"").unwrap();
        }
        assert!(validate_main_continuation_window_generated_tree(&root).is_ok());
        std::fs::write(
            generated.join("main_continuation_window_shape_dead.cu"),
            b"",
        )
        .unwrap();
        assert!(validate_main_continuation_window_generated_tree(&root).is_err());
        std::fs::remove_dir_all(root).unwrap();
    }
}
