//! Generated-kernel bank for width-three main continuations.

use std::path::{Path, PathBuf};

use super::main_continuation_window::MAIN_CONTINUATION_WINDOW_SHAPE_DEFINED_BITS;

/// `(compiled shape mask, minimum blocks per SM)`, sorted by mask.
///
/// The fused executor uses a separate bound because all nine selector warps share a block.
pub const MAIN_CONTINUATION_WINDOW_KERNEL_BANK: [(u16, u32); 7] = [
    (0x00, 4),
    (0x01, 4),
    (0x03, 4),
    (0x07, 4),
    (0x13, 4),
    (0x17, 4),
    (0x1f, 4),
];

/// Shape covering every continuation instruction, used for source partitions.
pub const MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK: u16 =
    MAIN_CONTINUATION_WINDOW_SHAPE_DEFINED_BITS;
/// Number of compiled shape entries in each continuation kernel family.
pub const MAIN_CONTINUATION_WINDOW_KERNEL_COUNT: usize = 7;
/// Threads per block for split publication/evaluation kernels.
pub const MAIN_CONTINUATION_WINDOW_BLOCK_THREADS: u32 = 96;
/// One warp per selector pair in the fused tile-owning executor.
pub const MAIN_CONTINUATION_WINDOW_FUSED_THREADS: u32 = 288;
pub const MAIN_CONTINUATION_WINDOW_FUSED_MIN_BLOCKS: u32 = 2;

const EXPECTED_MASKS: [u16; MAIN_CONTINUATION_WINDOW_KERNEL_COUNT] =
    [0x00, 0x01, 0x03, 0x07, 0x13, 0x17, 0x1f];
const GENERATED_HEADER: &str =
    "// @generated by generate_main_continuation_window_production; do not edit.";
const MANIFEST_HEADER_NAME: &str = "main_continuation_window_manifest.cuh";
const FUSED_UNIT_NAME: &str = "main_continuation_window_fused.cu";

/// Repo-relative directory containing the generated native bank.
pub const MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR: &str =
    "gpu/gkr/native/gkr/backward/main_continuation_window/generated";
/// Repo-relative path of the generated Rust FFI registry.
pub const MAIN_CONTINUATION_WINDOW_GENERATED_REGISTRY: &str =
    "gpu/gkr/src/backward/main_continuation/generated_registry.rs";

/// Repository root, resolved independently of the process working directory.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("resolve repository root from CARGO_MANIFEST_DIR")
        .to_path_buf()
}

pub fn main_continuation_window_kernel_symbol(mask: u16, min_blocks: u32) -> String {
    format!("ab_gkr_bwd_main_cont_window3_shape_{mask:02x}_b{min_blocks}_kernel")
}

pub fn main_continuation_window_x01_kernel_symbol(mask: u16, min_blocks: u32) -> String {
    format!("ab_gkr_bwd_main_cont_window3_shape_{mask:02x}_b{min_blocks}_x01_kernel")
}

pub fn main_continuation_window_publication_kernel_symbol(mask: u16, min_blocks: u32) -> String {
    format!("ab_gkr_bwd_main_cont_window3_shape_{mask:02x}_b{min_blocks}_publish_kernel")
}

pub fn main_continuation_window_translation_unit_name(mask: u16) -> String {
    format!("main_continuation_window_shape_{mask:02x}.cu")
}

fn fused_symbol(mask: u16, x01: bool) -> String {
    format!(
        "ab_gkr_main_cont_fused_{mask:02x}_b{MAIN_CONTINUATION_WINDOW_FUSED_MIN_BLOCKS}{}",
        if x01 { "_x01" } else { "" }
    )
}

fn render_fused_translation_unit() -> String {
    let mut out = format!("{GENERATED_HEADER}\n#include \"../fused_executor.cuh\"\n\nnamespace airbender::gkr::backward {{\n\n");
    for (mask, _) in MAIN_CONTINUATION_WINDOW_KERNEL_BANK {
        for x01 in [false, true] {
            out.push_str(&format!("AB_GKR_MAIN_CONT_DEFINE_FUSED({}, {mask:#04x}, {MAIN_CONTINUATION_WINDOW_FUSED_MIN_BLOCKS}, {x01}, false);\n", fused_symbol(mask, x01)));
        }
    }
    out.push_str(&format!("\nstatic_assert(BWD_MAIN_CONT_FUSED_THREADS == {MAIN_CONTINUATION_WINDOW_FUSED_THREADS}, \"fused continuation geometry drift\");\n\n}} // namespace airbender::gkr::backward\n"));
    out
}

pub fn main_continuation_window_generated_artifacts() -> Vec<(String, String)> {
    let mut artifacts = vec![(
        format!("{MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR}/{MANIFEST_HEADER_NAME}"),
        render_main_continuation_window_manifest(),
    )];
    for (mask, min_blocks) in MAIN_CONTINUATION_WINDOW_KERNEL_BANK {
        artifacts.push((
            format!(
                "{MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR}/{}",
                main_continuation_window_translation_unit_name(mask)
            ),
            render_main_continuation_window_translation_unit(mask, min_blocks),
        ));
    }
    artifacts.push((
        format!("{MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR}/{FUSED_UNIT_NAME}"),
        render_fused_translation_unit(),
    ));
    artifacts.push((
        MAIN_CONTINUATION_WINDOW_GENERATED_REGISTRY.to_owned(),
        render_main_continuation_window_registry(),
    ));
    artifacts
}

fn render_main_continuation_window_manifest() -> String {
    format!(
        "{GENERATED_HEADER}\n\
         #pragma once\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         inline constexpr unsigned BWD_MAIN_CONTINUATION_WINDOW_KERNEL_COUNT = {};\n\
         inline constexpr unsigned BWD_MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK = {:#04x};\n\
         \n\
         }} // namespace airbender::gkr::backward\n",
        MAIN_CONTINUATION_WINDOW_KERNEL_COUNT, MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK,
    )
}

pub fn render_main_continuation_window_translation_unit(mask: u16, min_blocks: u32) -> String {
    let symbol = main_continuation_window_kernel_symbol(mask, min_blocks);
    let x01_symbol = main_continuation_window_x01_kernel_symbol(mask, min_blocks);
    let publication_symbol = main_continuation_window_publication_kernel_symbol(mask, min_blocks);
    format!(
        "{GENERATED_HEADER}\n\
         #include \"../executor.cuh\"\n\
         #include \"{MANIFEST_HEADER_NAME}\"\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         AB_GKR_BWD_MAIN_CONT_WINDOW_DEFINE_PUBLICATION_KERNEL({publication_symbol});\n\
         AB_GKR_BWD_MAIN_CONT_WINDOW_DEFINE_KERNEL({symbol}, {mask:#04x}, {min_blocks});\n\
         AB_GKR_BWD_MAIN_CONT_WINDOW_DEFINE_X01_KERNEL({x01_symbol}, {mask:#04x}, {min_blocks});\n\
         \n\
         static_assert(BWD_MAIN_CONTINUATION_WINDOW_KERNEL_COUNT == {MAIN_CONTINUATION_WINDOW_KERNEL_COUNT}, \"shape_{mask:02x} continuation-window manifest drift\");\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

fn render_main_continuation_window_registry() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\n\n");
    out.push_str(
        "use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};\n\n",
    );
    out.push_str("use super::binding::MainContinuationWindowLaunchBinding;\n\n");
    out.push_str("/// Universal executor for well-formed masks absent from the exact bank.\n");
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK: u16 = {MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK:#04x};\n\n"
    ));
    out.push_str("/// Threads per block for split publication/evaluation kernels.\n");
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_BLOCK_THREADS: u32 = {MAIN_CONTINUATION_WINDOW_BLOCK_THREADS};\n\n"
    ));
    out.push_str(&format!("pub(crate) const MAIN_CONTINUATION_WINDOW_FUSED_THREADS: u32 = {MAIN_CONTINUATION_WINDOW_FUSED_THREADS};\n\n"));
    out.push_str(&format!("pub(crate) const MAIN_CONTINUATION_WINDOW_FUSED_MIN_BLOCKS: u32 = {MAIN_CONTINUATION_WINDOW_FUSED_MIN_BLOCKS};\n\n"));
    out.push_str("cuda_kernel_signature_arguments_and_function!(\n");
    out.push_str("    pub(crate) GkrBwdMainContinuationWindow3,\n");
    out.push_str("    desc: MainContinuationWindowLaunchBinding,\n");
    out.push_str(");\n\n");
    out.push_str("/// One generated continuation-window entry point.\n");
    out.push_str("pub(crate) struct MainContinuationWindowKernelEntry {\n");
    out.push_str("    pub mask: u16,\n");
    out.push_str("    pub publication_symbol: GkrBwdMainContinuationWindow3Signature,\n");
    out.push_str("    pub symbol: GkrBwdMainContinuationWindow3Signature,\n");
    out.push_str("    pub x01_symbol: GkrBwdMainContinuationWindow3Signature,\n");
    out.push_str("    pub fused_symbol: GkrBwdMainContinuationWindow3Signature,\n");
    out.push_str("    pub fused_x01_symbol: GkrBwdMainContinuationWindow3Signature,\n");
    out.push_str("}\n\n");
    for (mask, min_blocks) in MAIN_CONTINUATION_WINDOW_KERNEL_BANK {
        out.push_str(&format!(
            "cuda_kernel_declaration!(\n    pub(crate) {}(desc: MainContinuationWindowLaunchBinding)\n);\n",
            main_continuation_window_kernel_symbol(mask, min_blocks)
        ));
        out.push_str(&format!(
            "cuda_kernel_declaration!(\n    pub(crate) {}(desc: MainContinuationWindowLaunchBinding)\n);\n",
            main_continuation_window_publication_kernel_symbol(mask, min_blocks)
        ));
        out.push_str(&format!(
            "cuda_kernel_declaration!(\n    pub(crate) {}(desc: MainContinuationWindowLaunchBinding)\n);\n",
            main_continuation_window_x01_kernel_symbol(mask, min_blocks)
        ));
        for x01 in [false, true] {
            out.push_str(&format!("cuda_kernel_declaration!(\n    pub(crate) {}(desc: MainContinuationWindowLaunchBinding)\n);\n", fused_symbol(mask, x01)));
        }
    }
    out.push('\n');
    out.push_str(&format!(
        "pub(crate) const MAIN_CONTINUATION_WINDOW_KERNELS: [MainContinuationWindowKernelEntry; {}] = [\n",
        MAIN_CONTINUATION_WINDOW_KERNEL_COUNT
    ));
    for (mask, min_blocks) in MAIN_CONTINUATION_WINDOW_KERNEL_BANK {
        let symbol = main_continuation_window_kernel_symbol(mask, min_blocks);
        let x01_symbol = main_continuation_window_x01_kernel_symbol(mask, min_blocks);
        let publication_symbol =
            main_continuation_window_publication_kernel_symbol(mask, min_blocks);
        out.push_str("    MainContinuationWindowKernelEntry {\n");
        out.push_str(&format!("        mask: {mask:#04x},\n"));
        out.push_str(&format!(
            "        publication_symbol: {publication_symbol},\n"
        ));
        out.push_str(&format!("        symbol: {symbol},\n"));
        out.push_str(&format!("        x01_symbol: {x01_symbol},\n"));
        out.push_str(&format!(
            "        fused_symbol: {},\n",
            fused_symbol(mask, false)
        ));
        out.push_str(&format!(
            "        fused_x01_symbol: {},\n",
            fused_symbol(mask, true)
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n");
    out
}

fn expected_generated_native_entries() -> Vec<String> {
    let mut expected: Vec<String> = EXPECTED_MASKS
        .into_iter()
        .map(main_continuation_window_translation_unit_name)
        .collect();
    expected.push(MANIFEST_HEADER_NAME.to_owned());
    expected.push(FUSED_UNIT_NAME.to_owned());
    expected.sort();
    expected
}

/// Fail if the generated native directory contains a stale or extra file.
pub fn validate_main_continuation_window_generated_tree(root: &Path) -> Result<(), String> {
    let directory = root.join(MAIN_CONTINUATION_WINDOW_GENERATED_NATIVE_DIR);
    let mut present: Vec<String> = std::fs::read_dir(&directory)
        .map_err(|error| format!("{}: {error}", directory.display()))?
        .map(|entry| {
            entry
                .map_err(|error| error.to_string())
                .map(|entry| entry.file_name().to_string_lossy().into_owned())
        })
        .collect::<Result<_, _>>()?;
    present.sort();
    let expected = expected_generated_native_entries();
    if present != expected {
        return Err(format!(
            "generated native tree differs: present={present:?}, expected={expected:?}"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cpu_main_continuation_window_manifest_committed_artifacts_are_current() {
        let root = repo_root();
        for (relative, rendered) in main_continuation_window_generated_artifacts() {
            let committed = std::fs::read_to_string(root.join(&relative))
                .unwrap_or_else(|error| panic!("{relative}: {error}"));
            assert_eq!(
                committed, rendered,
                "{relative} is stale; rerun generate_main_continuation_window_production --write"
            );
        }
    }

    #[test]
    fn cpu_main_continuation_window_manifest_generated_tree_has_no_extra_files() {
        validate_main_continuation_window_generated_tree(&repo_root()).unwrap();
    }
}
