//! Production dispatch manifest for the windowed R0 executor.
//!
//! The map supplies baseline choices for fourteen native masks using four
//! kernels. Known universal programs reaching the weighted product score
//! threshold select guarded b3; all other entries retain their baseline choice.
//! A well-formed unknown mask keeps the fixed `0xfff` b4 fallback; undefined
//! feature bits are rejected because no kernel implements them.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use super::window::{
    WindowLoweringError, WindowShape, WINDOW_SECTION_WORDS, WINDOW_SHAPE_DEFINED_BITS,
};

/// `(native shape mask, compiled kernel mask, min blocks per SM)`.
pub const WINDOWED_R0_DISPATCH: [(u16, u16, u32); 14] = [
    (0x001, 0x471, 4),
    (0x020, 0xfff, 3),
    (0x1b1, 0xfff, 3),
    (0x1b7, 0xfff, 4),
    (0x3f7, 0xfff, 4),
    (0x3fb, 0xfff, 3),
    (0x460, 0xfff, 3),
    (0x470, 0xfff, 3),
    (0x4f6, 0x4f6, 3),
    (0x9bf, 0xfff, 4),
    (0xbfb, 0xfff, 3),
    (0xbff, 0xfff, 4),
    (0xc78, 0xfff, 3),
    (0xc7a, 0xfff, 3),
];

/// Every mask of defined feature bits is a subset of this one, so it can execute
/// any well-formed program the map does not name.
pub const WINDOWED_R0_UNIVERSAL_MASK: u16 = WINDOW_SHAPE_DEFINED_BITS;

/// Fixed entry for well-formed shapes absent from the dispatch map.
pub const WINDOWED_R0_FALLBACK: (u16, u32) = (WINDOWED_R0_UNIVERSAL_MASK, 4);

/// Generated entry points, including the fixed fallback.
pub const WINDOWED_R0_KERNEL_COUNT: usize = 4;

/// Threads per block every generated window kernel is compiled for.
pub const WINDOWED_R0_BLOCK_THREADS: u32 = 288;

const GENERATED_HEADER: &str = "// @generated by generate_windowed_r0_production; do not edit.";
const MANIFEST_HEADER_NAME: &str = "windowed_r0_manifest.cuh";

/// The generated bank: one `(mask, min_blocks)` per compiled kernel, ascending.
pub fn windowed_r0_bank() -> Vec<(u16, u32)> {
    let mut bank = BTreeSet::from([WINDOWED_R0_FALLBACK]);
    for (_, mask, min_blocks) in WINDOWED_R0_DISPATCH {
        bank.insert((mask, min_blocks));
    }
    bank.into_iter().collect()
}

/// Resolve one lowered shape mask to its compiled kernel.
pub fn resolve_windowed_r0_dispatch(mask: u16) -> Result<(u16, u32), WindowLoweringError> {
    WindowShape::from_bits(mask)?;
    if let Some((_, compiled, min_blocks)) = WINDOWED_R0_DISPATCH
        .iter()
        .find(|(native, ..)| *native == mask)
    {
        return Ok((*compiled, *min_blocks));
    }
    Ok(WINDOWED_R0_FALLBACK)
}

/// Empirical reuse thresholds shared with the native executor through codegen.
/// These are atom-count cutoffs, not cache-capacity bounds.
pub const WINDOWED_R0_REUSE_SCORE: u32 = 120;
pub const WINDOWED_R0_REUSE_SINGLETONS: u32 = 16;

/// Whether the program reaches the weighted product threshold for b3 selection.
/// The executor also guards singleton-only programs; that lower threshold does
/// not justify changing b4 dispatch (bigint and Keccak are counterexamples).
/// Endpoints come from a validated lowered program. Match CUDA u32 arithmetic.
pub fn windowed_r0_prefers_guarded_b3(sections: &[u32; WINDOW_SECTION_WORDS]) -> bool {
    let singletons = sections[2] - sections[1];
    let pairs = (sections[3] - sections[2]) / 3;
    singletons
        .wrapping_mul(2)
        .wrapping_add(pairs.wrapping_mul(4))
        >= WINDOWED_R0_REUSE_SCORE
}

/// Select guarded b3 for reuse-heavy known universal programs. All other mask
/// choices, dedicated kernels, and the unknown-mask fallback stay fixed.
pub fn resolve_windowed_r0_program_dispatch(
    mask: u16,
    sections: &[u32; WINDOW_SECTION_WORDS],
) -> Result<(u16, u32), WindowLoweringError> {
    let entry = resolve_windowed_r0_dispatch(mask)?;
    if entry.0 == WINDOWED_R0_UNIVERSAL_MASK
        && WINDOWED_R0_DISPATCH.iter().any(|row| row.0 == mask)
        && windowed_r0_prefers_guarded_b3(sections)
    {
        Ok((entry.0, 3))
    } else {
        Ok(entry)
    }
}

/// Validate native masks, compatible compiled entries, and bank size.
pub fn validate_windowed_r0_dispatch() -> Result<(), String> {
    let mut natives = BTreeMap::new();
    for (native, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
        if natives.insert(native, (compiled, min_blocks)).is_some() {
            return Err(format!("duplicate native mask {native:#05x}"));
        }
        if native & !WINDOW_SHAPE_DEFINED_BITS != 0 {
            return Err(format!("native mask {native:#05x} carries undefined bits"));
        }
        if compiled & !WINDOW_SHAPE_DEFINED_BITS != 0 {
            return Err(format!(
                "compiled mask {compiled:#05x} carries undefined bits"
            ));
        }
        if native & compiled != native {
            return Err(format!(
                "native mask {native:#05x} is not a subset of compiled mask {compiled:#05x}"
            ));
        }
        if !matches!(min_blocks, 3 | 4) {
            return Err(format!(
                "compiled mask {compiled:#05x} has unsupported launch bound {min_blocks}"
            ));
        }
    }
    let bank = windowed_r0_bank();
    if bank.len() != WINDOWED_R0_KERNEL_COUNT {
        return Err(format!(
            "dispatch bank is {} entries, expected {WINDOWED_R0_KERNEL_COUNT}",
            bank.len()
        ));
    }
    Ok(())
}

pub fn windowed_r0_kernel_symbol(mask: u16, min_blocks: u32) -> String {
    format!("ab_gkr_bwd_r0_window3_shape_{mask:03x}_b{min_blocks}_kernel")
}

pub fn windowed_r0_translation_unit_name(mask: u16, min_blocks: u32) -> String {
    format!("r0_window_shape_{mask:03x}_b{min_blocks}.cu")
}

/// Repository root, resolved from `CARGO_MANIFEST_DIR` so the process working
/// directory does not matter.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("resolve repository root from CARGO_MANIFEST_DIR")
        .to_path_buf()
}

/// Repo-relative path of the native generated tree.
pub const WINDOWED_R0_GENERATED_NATIVE_DIR: &str = "gpu/gkr/native/gkr/backward/generated";
/// Repo-relative path of the generated Rust FFI registry.
pub const WINDOWED_R0_GENERATED_REGISTRY: &str =
    "gpu/gkr/src/backward/window/generated_registry.rs";

/// Every committed generated artifact as `(repo-relative path, contents)`.
pub fn windowed_r0_generated_artifacts() -> Result<Vec<(String, String)>, String> {
    validate_windowed_r0_dispatch()?;
    let mut artifacts = vec![(
        format!("{WINDOWED_R0_GENERATED_NATIVE_DIR}/{MANIFEST_HEADER_NAME}"),
        render_windowed_r0_manifest(),
    )];
    for (mask, min_blocks) in windowed_r0_bank() {
        artifacts.push((
            format!(
                "{WINDOWED_R0_GENERATED_NATIVE_DIR}/{}",
                windowed_r0_translation_unit_name(mask, min_blocks)
            ),
            render_windowed_r0_translation_unit(mask, min_blocks),
        ));
    }
    artifacts.push((
        WINDOWED_R0_GENERATED_REGISTRY.to_owned(),
        render_windowed_r0_registry(),
    ));
    Ok(artifacts)
}

pub fn render_windowed_r0_manifest() -> String {
    let rows = WINDOWED_R0_DISPATCH.len();
    format!(
        "{GENERATED_HEADER}\n\
         #pragma once\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         inline constexpr unsigned BWD_WINDOW_R0_KERNEL_COUNT = {WINDOWED_R0_KERNEL_COUNT};\n\
         inline constexpr unsigned BWD_WINDOW_R0_DISPATCH_ROWS = {rows};\n\
         inline constexpr unsigned BWD_WINDOW_R0_REUSE_SCORE = {WINDOWED_R0_REUSE_SCORE};\n\
         inline constexpr unsigned BWD_WINDOW_R0_REUSE_SINGLETONS = {WINDOWED_R0_REUSE_SINGLETONS};\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_windowed_r0_translation_unit(mask: u16, min_blocks: u32) -> String {
    let symbol = windowed_r0_kernel_symbol(mask, min_blocks);
    format!(
        "{GENERATED_HEADER}\n\
         #include \"../window/window_control.cuh\"\n\
         #include \"{MANIFEST_HEADER_NAME}\"\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         AB_GKR_BWD_WINDOW_DEFINE_KERNEL({symbol}, {mask:#05x}, {min_blocks});\n\
         \n\
         static_assert(BWD_WINDOW_R0_KERNEL_COUNT == {WINDOWED_R0_KERNEL_COUNT}, \
         \"shape_{mask:03x} window manifest drift\");\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_windowed_r0_registry() -> String {
    let bank = windowed_r0_bank();
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\n\n");
    out.push_str("use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};\n\n");
    out.push_str("use super::binding::WindowLaunchBinding;\n\n");
    out.push_str(
        "/// `(native shape mask, compiled kernel mask, min blocks per SM)`, mirroring\n\
         /// `gpu_gkr_compiler::backward::WINDOWED_R0_DISPATCH`.\n",
    );
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_DISPATCH: [(u16, u16, u32); {}] = [\n",
        WINDOWED_R0_DISPATCH.len()
    ));
    for (native, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
        out.push_str(&format!(
            "    ({native:#05x}, {compiled:#05x}, {min_blocks}),\n"
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// Fixed universal entry for a shape absent from the dispatch map.\n");
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_FALLBACK: (u16, u32) = ({:#05x}, {});\n\n",
        WINDOWED_R0_FALLBACK.0, WINDOWED_R0_FALLBACK.1
    ));
    out.push_str("/// Threads per block every generated window kernel is compiled for.\n");
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_BLOCK_THREADS: u32 = {WINDOWED_R0_BLOCK_THREADS};\n\n"
    ));
    out.push_str("cuda_kernel_signature_arguments_and_function!(\n");
    out.push_str("    pub(crate) GkrBwdR0Window3,\n");
    out.push_str("    desc: WindowLaunchBinding,\n");
    out.push_str(");\n\n");
    out.push_str("pub(crate) struct WindowKernelEntry {\n");
    out.push_str("    pub mask: u16,\n");
    out.push_str("    pub min_blocks: u32,\n");
    out.push_str("    pub symbol: GkrBwdR0Window3Signature,\n");
    out.push_str("}\n\n");
    for (mask, min_blocks) in &bank {
        out.push_str(&format!(
            "cuda_kernel_declaration!(\n    pub(crate) {}(desc: WindowLaunchBinding)\n);\n",
            windowed_r0_kernel_symbol(*mask, *min_blocks)
        ));
    }
    out.push('\n');
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_KERNELS: [WindowKernelEntry; {}] = [\n",
        bank.len()
    ));
    for (mask, min_blocks) in &bank {
        let symbol = windowed_r0_kernel_symbol(*mask, *min_blocks);
        out.push_str("    WindowKernelEntry {\n");
        out.push_str(&format!("        mask: {mask:#05x},\n"));
        out.push_str(&format!("        min_blocks: {min_blocks},\n"));
        out.push_str(&format!("        symbol: {symbol},\n"));
        out.push_str("    },\n");
    }
    out.push_str("];\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cpu_program_selector_boundaries_and_fixed_entries() {
        // Weighted-score boundaries and singleton-only counterexamples, plus u32 wrap.
        for (singletons, pairs, reuse) in [
            (0, 0, false),
            (15, 0, false),
            (16, 0, false),
            (59, 0, false),
            (60, 0, true),
            (57, 1, false),
            (58, 1, true),
            (59, 1, true),
            (0, 29, false),
            (0, 30, true),
            (u32::MAX - 3, 1, true),
            (1 << 31, 1, false),
        ] {
            let mut sections = [0; WINDOW_SECTION_WORDS];
            sections[2] = singletons;
            sections[3] = singletons + 3 * pairs;
            assert_eq!(windowed_r0_prefers_guarded_b3(&sections), reuse);
            for mask in 0..=WINDOW_SHAPE_DEFINED_BITS {
                let fixed = resolve_windowed_r0_dispatch(mask).unwrap();
                let expected = if reuse
                    && fixed.0 == WINDOWED_R0_UNIVERSAL_MASK
                    && WINDOWED_R0_DISPATCH.iter().any(|row| row.0 == mask)
                {
                    (0xfff, 3)
                } else {
                    fixed
                };
                assert_eq!(
                    resolve_windowed_r0_program_dispatch(mask, &sections).unwrap(),
                    expected,
                    "mask {mask:03x}, singletons={singletons}, pairs={pairs}"
                );
            }
        }
        assert!(resolve_windowed_r0_program_dispatch(0x1000, &[0; WINDOW_SECTION_WORDS]).is_err());
    }

    #[test]
    fn cpu_dispatch_is_well_formed() {
        validate_windowed_r0_dispatch().unwrap();
    }

    #[test]
    fn cpu_every_native_mask_resolves_to_its_ruled_kernel() {
        for (native, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
            assert_eq!(
                resolve_windowed_r0_dispatch(native).unwrap(),
                (compiled, min_blocks),
                "native {native:#05x}"
            );
        }
    }

    #[test]
    fn cpu_unnamed_well_formed_masks_use_the_universal_kernel() {
        let named: Vec<u16> = WINDOWED_R0_DISPATCH.iter().map(|row| row.0).collect();
        let mut checked = 0usize;
        for mask in 0..=WINDOW_SHAPE_DEFINED_BITS {
            if named.contains(&mask) {
                continue;
            }
            assert_eq!(
                resolve_windowed_r0_dispatch(mask).unwrap(),
                (WINDOWED_R0_UNIVERSAL_MASK, 4),
                "mask {mask:#05x}"
            );
            checked += 1;
        }
        assert_eq!(checked, 4096 - named.len());
    }

    #[test]
    fn cpu_undefined_feature_bits_are_rejected() {
        for bit in 12..16u32 {
            let mask = 1u16 << bit;
            assert!(matches!(
                resolve_windowed_r0_dispatch(mask),
                Err(WindowLoweringError::UndefinedShapeBits { bits }) if bits == mask
            ));
            assert!(matches!(
                resolve_windowed_r0_dispatch(WINDOWED_R0_UNIVERSAL_MASK | mask),
                Err(WindowLoweringError::UndefinedShapeBits { .. })
            ));
        }
    }

    #[test]
    fn cpu_bank_preserves_both_universal_entries() {
        let bank = windowed_r0_bank();
        assert!(bank.contains(&(WINDOWED_R0_UNIVERSAL_MASK, 3)));
        assert!(bank.contains(&(WINDOWED_R0_UNIVERSAL_MASK, 4)));
        let names: BTreeSet<_> = bank
            .iter()
            .map(|&(mask, bound)| windowed_r0_translation_unit_name(mask, bound))
            .collect();
        assert_eq!(
            names.len(),
            bank.len(),
            "translation-unit paths must be unique"
        );
    }

    #[test]
    fn cpu_committed_generated_artifacts_are_current() {
        let root = repo_root();
        let artifacts = windowed_r0_generated_artifacts().unwrap();
        assert_eq!(artifacts.len(), WINDOWED_R0_KERNEL_COUNT + 2);
        let expected: BTreeSet<_> = artifacts
            .iter()
            .filter_map(|(relative, _)| {
                relative
                    .ends_with(".cu")
                    .then(|| Path::new(relative).file_name().unwrap().to_owned())
            })
            .collect();
        let present: BTreeSet<_> = std::fs::read_dir(root.join(WINDOWED_R0_GENERATED_NATIVE_DIR))
            .unwrap()
            .map(|entry| entry.unwrap().file_name())
            .filter(|name| {
                name.to_str()
                    .is_some_and(|s| s.starts_with("r0_window_shape_") && s.ends_with(".cu"))
            })
            .collect();
        assert_eq!(
            present, expected,
            "obsolete or missing R0 translation units"
        );
        for (relative, rendered) in artifacts {
            let path = root.join(&relative);
            let committed = std::fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("{relative}: {error}"));
            assert_eq!(
                committed, rendered,
                "{relative} is stale; rerun generate_windowed_r0_production --write"
            );
        }
    }
}
