//! Authoritative generated surface for the universal dimension-reducing R0
//! window producer.

use std::path::{Path, PathBuf};

/// Five fixed dimension-reducing slots are selected by bits 0 through 4.
pub const DR_WINDOWED_R0_DEFINED_MASK: u32 = (1 << 5) - 1;
/// Masks observed across the retained 229-layer production corpus.
pub const DR_WINDOWED_R0_OBSERVED_MASKS: [u32; 4] = [0x01, 0x0d, 0x0f, 0x1f];
/// Every valid mask selects this one universal entry point.
pub const DR_WINDOWED_R0_KERNEL_SYMBOL: &str = "ab_gkr_dr_r0_window3_universal_kernel";
/// Nine warps: one for each pair in `{0, 1, infinity}^2`.
pub const DR_WINDOWED_R0_BLOCK_THREADS: u32 = 288;

const GENERATED_HEADER: &str = "// @generated by generate_dr_windowed_r0_production; do not edit.";
#[cfg(test)]
const GENERATED_NATIVE_DIR: &str = "gpu/gkr/native/gkr/backward/generated";
const MANIFEST_PATH: &str = "gpu/gkr/native/gkr/backward/generated/dr_windowed_r0_manifest.cuh";
const TRANSLATION_UNIT_PATH: &str =
    "gpu/gkr/native/gkr/backward/generated/dr_r0_window_universal.cu";
const REGISTRY_PATH: &str = "gpu/gkr/src/backward/window_dr/generated_registry.rs";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DrWindowManifestError {
    ZeroMask,
    UndefinedMaskBits { bits: u32 },
}

impl core::fmt::Display for DrWindowManifestError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(formatter, "{self:?}")
    }
}

impl std::error::Error for DrWindowManifestError {}

/// Resolve every well-formed, nonzero five-bit mask to the universal symbol.
pub fn resolve_dr_windowed_r0_dispatch(mask: u32) -> Result<&'static str, DrWindowManifestError> {
    let undefined = mask & !DR_WINDOWED_R0_DEFINED_MASK;
    if undefined != 0 {
        return Err(DrWindowManifestError::UndefinedMaskBits { bits: undefined });
    }
    if mask == 0 {
        return Err(DrWindowManifestError::ZeroMask);
    }
    Ok(DR_WINDOWED_R0_KERNEL_SYMBOL)
}

pub fn validate_dr_windowed_r0_dispatch() -> Result<(), String> {
    for mask in 1..=DR_WINDOWED_R0_DEFINED_MASK {
        let symbol = resolve_dr_windowed_r0_dispatch(mask).map_err(|error| error.to_string())?;
        if symbol != DR_WINDOWED_R0_KERNEL_SYMBOL {
            return Err(format!("mask {mask:#04x} resolves to {symbol}"));
        }
    }
    if !DR_WINDOWED_R0_OBSERVED_MASKS
        .iter()
        .all(|mask| (1..=DR_WINDOWED_R0_DEFINED_MASK).contains(mask))
    {
        return Err("an observed DR mask is outside the defined five-bit domain".to_owned());
    }
    Ok(())
}

pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("resolve repository root from CARGO_MANIFEST_DIR")
        .to_path_buf()
}

pub fn render_dr_windowed_r0_manifest() -> String {
    format!(
        "{GENERATED_HEADER}\n\
         #pragma once\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         inline constexpr unsigned DR_WINDOW_R0_DEFINED_MASK = {DR_WINDOWED_R0_DEFINED_MASK:#04x};\n\
         inline constexpr unsigned DR_WINDOW_R0_BLOCK_THREADS = {DR_WINDOWED_R0_BLOCK_THREADS};\n\
         inline constexpr unsigned DR_WINDOW_R0_KERNEL_COUNT = 1;\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_dr_windowed_r0_translation_unit() -> String {
    format!(
        "{GENERATED_HEADER}\n\
         #include \"../window_dr/r0.cuh\"\n\
         #include \"dr_windowed_r0_manifest.cuh\"\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         EXTERN __global__ __launch_bounds__(DR_WINDOW_R0_BLOCK_THREADS) void {DR_WINDOWED_R0_KERNEL_SYMBOL}(const __grid_constant__ gkr_dr_window3_desc desc) {{\n\
         \x20\x20dr_window_r0(desc);\n\
         }}\n\
         \n\
         static_assert(DR_WINDOW_R0_KERNEL_COUNT == 1, \"DR R0 manifest drift\");\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_dr_windowed_r0_registry() -> String {
    let mut out = format!(
        "{GENERATED_HEADER}\n\n\
         use era_cudart::{{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function}};\n\n\
         use super::binding::DrWindowLaunchBinding;\n\n\
         // Task 4's binder consumes the generated dispatch domain.\n\
         pub(crate) const DR_WINDOWED_R0_DEFINED_MASK: u32 = {DR_WINDOWED_R0_DEFINED_MASK:#04x};\n\
         // Task 4's launcher consumes the generated block geometry.\n\
         pub(crate) const DR_WINDOWED_R0_BLOCK_THREADS: u32 = {DR_WINDOWED_R0_BLOCK_THREADS};\n\n\
         cuda_kernel_signature_arguments_and_function!(\n\
         pub(crate) GkrDrR0Window3,\n\
         desc: DrWindowLaunchBinding,\n\
         );\n\n\
         // Task 4's binder and launcher consume this generated entry.\n\
         pub(crate) struct DrWindowKernelEntry {{\n"
    );
    out.push_str("    pub symbol_name: &'static str,\n");
    out.push_str("    pub symbol: GkrDrR0Window3Signature,\n");
    out.push_str("}\n\n");
    out.push_str("cuda_kernel_declaration!(\n");
    out.push_str(&format!(
        "pub(crate) {DR_WINDOWED_R0_KERNEL_SYMBOL}(desc: DrWindowLaunchBinding)\n"
    ));
    out.push_str(");\n\n");
    out.push_str("// Task 4's binder selects this entry for every valid mask.\n");
    out.push_str("pub(crate) const DR_WINDOWED_R0_UNIVERSAL_KERNEL: DrWindowKernelEntry = DrWindowKernelEntry {\n");
    out.push_str(&format!(
        "    symbol_name: \"{DR_WINDOWED_R0_KERNEL_SYMBOL}\",\n"
    ));
    out.push_str(&format!("    symbol: {DR_WINDOWED_R0_KERNEL_SYMBOL},\n"));
    out.push_str("};\n");
    out
}

/// The exact three committed artifacts owned by the DR-specific generator.
pub fn dr_windowed_r0_generated_artifacts() -> Result<Vec<(String, String)>, String> {
    validate_dr_windowed_r0_dispatch()?;
    Ok(vec![
        (MANIFEST_PATH.to_owned(), render_dr_windowed_r0_manifest()),
        (
            TRANSLATION_UNIT_PATH.to_owned(),
            render_dr_windowed_r0_translation_unit(),
        ),
        (REGISTRY_PATH.to_owned(), render_dr_windowed_r0_registry()),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cpu_dr_windowed_r0_generated_dispatch_covers_all_nonzero_five_bit_masks() {
        validate_dr_windowed_r0_dispatch().unwrap();
        for mask in 1..=DR_WINDOWED_R0_DEFINED_MASK {
            assert_eq!(
                resolve_dr_windowed_r0_dispatch(mask),
                Ok(DR_WINDOWED_R0_KERNEL_SYMBOL),
                "mask {mask:#04x}",
            );
        }
    }

    #[test]
    fn cpu_dr_windowed_r0_generated_dispatch_rejects_zero_and_undefined_masks() {
        assert_eq!(
            resolve_dr_windowed_r0_dispatch(0),
            Err(DrWindowManifestError::ZeroMask),
        );
        for bit in 5..32 {
            let undefined = 1u32 << bit;
            assert_eq!(
                resolve_dr_windowed_r0_dispatch(undefined),
                Err(DrWindowManifestError::UndefinedMaskBits { bits: undefined }),
            );
            assert_eq!(
                resolve_dr_windowed_r0_dispatch(DR_WINDOWED_R0_DEFINED_MASK | undefined),
                Err(DrWindowManifestError::UndefinedMaskBits { bits: undefined }),
            );
        }
    }

    #[test]
    fn cpu_dr_windowed_r0_generated_artifacts_are_current() {
        let artifacts = dr_windowed_r0_generated_artifacts().unwrap();
        assert_eq!(artifacts.len(), 3);
        for (relative, rendered) in artifacts {
            let committed = std::fs::read_to_string(repo_root().join(&relative))
                .unwrap_or_else(|error| panic!("{relative}: {error}"));
            assert_eq!(
                committed, rendered,
                "{relative} is stale; rerun generate_dr_windowed_r0_production --write",
            );
        }
    }

    #[test]
    fn cpu_dr_windowed_r0_generated_paths_do_not_overlap_main_r0() {
        let paths = dr_windowed_r0_generated_artifacts()
            .unwrap()
            .into_iter()
            .map(|(path, _)| path)
            .collect::<Vec<_>>();
        assert_eq!(
            paths,
            vec![
                MANIFEST_PATH.to_owned(),
                TRANSLATION_UNIT_PATH.to_owned(),
                REGISTRY_PATH.to_owned(),
            ],
        );
        assert!(
            paths
                .iter()
                .filter(|path| path.starts_with(GENERATED_NATIVE_DIR))
                .count()
                == 2
        );
        assert!(paths.iter().all(|path| !path.contains("window/")));
    }
}
