//! Production dispatch manifest for the windowed R0 executor.
//!
//! Dispatch is a pure function of a lowered program's shape mask. The map below
//! is the RULED selection: fourteen native masks — the retained circuit corpus
//! is exactly those fourteen — each sent to one compiled mask at one launch
//! bound, with an eleven-kernel image. A well-formed mask the map does not name
//! uses the universal `0xfff` entry; a mask carrying an undefined
//! feature bit is rejected, because the universal kernel cannot implement
//! semantics it has never heard of.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::window::{WindowLoweringError, WindowShape, WINDOW_SHAPE_DEFINED_BITS};

/// `(native shape mask, compiled kernel mask, min blocks per SM)`.
pub const WINDOWED_R0_DISPATCH: [(u16, u16, u32); 14] = [
    (0x001, 0x471, 4),
    (0x020, 0x4f6, 3),
    (0x1b1, 0x1b1, 3),
    (0x1b7, 0x5f7, 4),
    (0x3f7, 0x7ff, 4),
    (0x3fb, 0x3ff, 4),
    (0x460, 0xc78, 3),
    (0x470, 0x7f7, 3),
    (0x4f6, 0x4f6, 3),
    (0x9bf, 0xfff, 4),
    (0xbfb, 0xffb, 4),
    (0xbff, 0xfff, 4),
    (0xc78, 0xc7a, 3),
    (0xc7a, 0xc7a, 3),
];

/// Every mask of defined feature bits is a subset of this one, so it can execute
/// any well-formed program the map does not name.
pub const WINDOWED_R0_UNIVERSAL_MASK: u16 = WINDOW_SHAPE_DEFINED_BITS;

/// Generated entry points, i.e. the size of the dispatch map's image.
pub const WINDOWED_R0_KERNEL_COUNT: usize = 11;

/// Threads per block every generated window kernel is compiled for.
pub const WINDOWED_R0_BLOCK_THREADS: u32 = 288;

const GENERATED_HEADER: &str = "// @generated by generate_windowed_r0_production; do not edit.";
const MANIFEST_HEADER_NAME: &str = "windowed_r0_manifest.cuh";

/// The generated bank: one `(mask, min_blocks)` per compiled kernel, ascending.
pub fn windowed_r0_bank() -> Vec<(u16, u32)> {
    let mut bank = BTreeMap::new();
    for (_, mask, min_blocks) in WINDOWED_R0_DISPATCH {
        bank.insert(mask, min_blocks);
    }
    bank.into_iter().collect()
}

/// Resolve one lowered shape mask to its compiled kernel.
pub fn resolve_windowed_r0_dispatch(mask: u16) -> Result<(u16, u32), WindowLoweringError> {
    WindowShape::from_bits(mask)?;
    if let Some((_, compiled, min_blocks)) = WINDOWED_R0_DISPATCH
        .iter()
        .find(|(native, ..)| *native == mask)
    {
        return Ok((*compiled, *min_blocks));
    }
    let min_blocks = windowed_r0_bank()
        .into_iter()
        .find(|(bank_mask, _)| *bank_mask == WINDOWED_R0_UNIVERSAL_MASK)
        .map(|(_, min_blocks)| min_blocks)
        .ok_or_else(|| {
            WindowLoweringError::Encoding("the dispatch bank omits the universal mask".to_owned())
        })?;
    Ok((WINDOWED_R0_UNIVERSAL_MASK, min_blocks))
}

/// The properties the ruling fixes, checked as data rather than trusted.
pub fn validate_windowed_r0_dispatch() -> Result<(), String> {
    let mut natives = BTreeMap::new();
    for (native, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
        if natives.insert(native, (compiled, min_blocks)).is_some() {
            return Err(format!("duplicate native mask {native:#05x}"));
        }
        if native & !WINDOW_SHAPE_DEFINED_BITS != 0 {
            return Err(format!("native mask {native:#05x} carries undefined bits"));
        }
        if compiled & !WINDOW_SHAPE_DEFINED_BITS != 0 {
            return Err(format!(
                "compiled mask {compiled:#05x} carries undefined bits"
            ));
        }
        if native & compiled != native {
            return Err(format!(
                "native mask {native:#05x} is not a subset of compiled mask {compiled:#05x}"
            ));
        }
        if !matches!(min_blocks, 3 | 4) {
            return Err(format!(
                "compiled mask {compiled:#05x} has unsupported launch bound {min_blocks}"
            ));
        }
    }
    let mut bounds: BTreeMap<u16, u32> = BTreeMap::new();
    for (_, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
        if let Some(previous) = bounds.insert(compiled, min_blocks) {
            if previous != min_blocks {
                return Err(format!(
                    "compiled mask {compiled:#05x} appears at both bounds {previous} and {min_blocks}"
                ));
            }
        }
    }
    if bounds.len() != WINDOWED_R0_KERNEL_COUNT {
        return Err(format!(
            "dispatch image is {} masks, expected {WINDOWED_R0_KERNEL_COUNT}",
            bounds.len()
        ));
    }
    if !bounds.contains_key(&WINDOWED_R0_UNIVERSAL_MASK) {
        return Err(format!(
            "the universal mask {WINDOWED_R0_UNIVERSAL_MASK:#05x} is not in the bank"
        ));
    }
    Ok(())
}

pub fn windowed_r0_kernel_symbol(mask: u16, min_blocks: u32) -> String {
    format!("ab_gkr_bwd_r0_window3_shape_{mask:03x}_b{min_blocks}_kernel")
}

pub fn windowed_r0_translation_unit_name(mask: u16) -> String {
    format!("r0_window_shape_{mask:03x}.cu")
}

/// Repository root, resolved from `CARGO_MANIFEST_DIR` so the process working
/// directory does not matter.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("resolve repository root from CARGO_MANIFEST_DIR")
        .to_path_buf()
}

/// Repo-relative path of the native generated tree.
pub const WINDOWED_R0_GENERATED_NATIVE_DIR: &str = "gpu/gkr/native/gkr/backward/generated";
/// Repo-relative path of the generated Rust FFI registry.
pub const WINDOWED_R0_GENERATED_REGISTRY: &str =
    "gpu/gkr/src/backward/window/generated_registry.rs";

/// Every committed generated artifact as `(repo-relative path, contents)`.
pub fn windowed_r0_generated_artifacts() -> Result<Vec<(String, String)>, String> {
    validate_windowed_r0_dispatch()?;
    let mut artifacts = vec![(
        format!("{WINDOWED_R0_GENERATED_NATIVE_DIR}/{MANIFEST_HEADER_NAME}"),
        render_windowed_r0_manifest(),
    )];
    for (mask, min_blocks) in windowed_r0_bank() {
        artifacts.push((
            format!(
                "{WINDOWED_R0_GENERATED_NATIVE_DIR}/{}",
                windowed_r0_translation_unit_name(mask)
            ),
            render_windowed_r0_translation_unit(mask, min_blocks),
        ));
    }
    artifacts.push((
        WINDOWED_R0_GENERATED_REGISTRY.to_owned(),
        render_windowed_r0_registry(),
    ));
    Ok(artifacts)
}

pub fn render_windowed_r0_manifest() -> String {
    let rows = WINDOWED_R0_DISPATCH.len();
    format!(
        "{GENERATED_HEADER}\n\
         #pragma once\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         inline constexpr unsigned BWD_WINDOW_R0_KERNEL_COUNT = {WINDOWED_R0_KERNEL_COUNT};\n\
         inline constexpr unsigned BWD_WINDOW_R0_DISPATCH_ROWS = {rows};\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_windowed_r0_translation_unit(mask: u16, min_blocks: u32) -> String {
    let symbol = windowed_r0_kernel_symbol(mask, min_blocks);
    format!(
        "{GENERATED_HEADER}\n\
         #include \"../window/window_control.cuh\"\n\
         #include \"{MANIFEST_HEADER_NAME}\"\n\
         \n\
         namespace airbender::gkr::backward {{\n\
         \n\
         AB_GKR_BWD_WINDOW_DEFINE_KERNEL({symbol}, {mask:#05x}, {min_blocks});\n\
         \n\
         static_assert(BWD_WINDOW_R0_KERNEL_COUNT == {WINDOWED_R0_KERNEL_COUNT}, \
         \"shape_{mask:03x} window manifest drift\");\n\
         \n\
         }} // namespace airbender::gkr::backward\n"
    )
}

pub fn render_windowed_r0_registry() -> String {
    let bank = windowed_r0_bank();
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\n\n");
    out.push_str("use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};\n\n");
    out.push_str("use super::binding::WindowLaunchBinding;\n\n");
    out.push_str(
        "/// `(native shape mask, compiled kernel mask, min blocks per SM)`, mirroring\n\
         /// `gpu_gkr_compiler::backward::WINDOWED_R0_DISPATCH`.\n",
    );
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_DISPATCH: [(u16, u16, u32); {}] = [\n",
        WINDOWED_R0_DISPATCH.len()
    ));
    for (native, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
        out.push_str(&format!(
            "    ({native:#05x}, {compiled:#05x}, {min_blocks}),\n"
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// Universal compiled mask for a shape the dispatch map does not name.\n");
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_UNIVERSAL_MASK: u16 = {WINDOWED_R0_UNIVERSAL_MASK:#05x};\n\n"
    ));
    out.push_str("/// Threads per block every generated window kernel is compiled for.\n");
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_BLOCK_THREADS: u32 = {WINDOWED_R0_BLOCK_THREADS};\n\n"
    ));
    out.push_str("cuda_kernel_signature_arguments_and_function!(\n");
    out.push_str("    pub(crate) GkrBwdR0Window3,\n");
    out.push_str("    desc: WindowLaunchBinding,\n");
    out.push_str(");\n\n");
    out.push_str("pub(crate) struct WindowKernelEntry {\n");
    out.push_str("    pub mask: u16,\n");
    out.push_str("    pub min_blocks: u32,\n");
    out.push_str("    pub symbol: GkrBwdR0Window3Signature,\n");
    out.push_str("}\n\n");
    for (mask, min_blocks) in &bank {
        out.push_str(&format!(
            "cuda_kernel_declaration!(\n    pub(crate) {}(desc: WindowLaunchBinding)\n);\n",
            windowed_r0_kernel_symbol(*mask, *min_blocks)
        ));
    }
    out.push('\n');
    out.push_str(&format!(
        "pub(crate) const WINDOWED_R0_KERNELS: [WindowKernelEntry; {}] = [\n",
        bank.len()
    ));
    for (mask, min_blocks) in &bank {
        let symbol = windowed_r0_kernel_symbol(*mask, *min_blocks);
        out.push_str("    WindowKernelEntry {\n");
        out.push_str(&format!("        mask: {mask:#05x},\n"));
        out.push_str(&format!("        min_blocks: {min_blocks},\n"));
        out.push_str(&format!("        symbol: {symbol},\n"));
        out.push_str("    },\n");
    }
    out.push_str("];\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cpu_dispatch_is_well_formed() {
        validate_windowed_r0_dispatch().unwrap();
    }

    #[test]
    fn cpu_every_native_mask_resolves_to_its_ruled_kernel() {
        for (native, compiled, min_blocks) in WINDOWED_R0_DISPATCH {
            assert_eq!(
                resolve_windowed_r0_dispatch(native).unwrap(),
                (compiled, min_blocks),
                "native {native:#05x}"
            );
        }
    }

    #[test]
    fn cpu_unnamed_well_formed_masks_use_the_universal_kernel() {
        let named: Vec<u16> = WINDOWED_R0_DISPATCH.iter().map(|row| row.0).collect();
        let mut checked = 0usize;
        for mask in 0..=WINDOW_SHAPE_DEFINED_BITS {
            if named.contains(&mask) {
                continue;
            }
            assert_eq!(
                resolve_windowed_r0_dispatch(mask).unwrap(),
                (WINDOWED_R0_UNIVERSAL_MASK, 4),
                "mask {mask:#05x}"
            );
            checked += 1;
        }
        assert_eq!(checked, 4096 - named.len());
    }

    #[test]
    fn cpu_undefined_feature_bits_are_rejected() {
        for bit in 12..16u32 {
            let mask = 1u16 << bit;
            assert!(matches!(
                resolve_windowed_r0_dispatch(mask),
                Err(WindowLoweringError::UndefinedShapeBits { bits }) if bits == mask
            ));
            assert!(matches!(
                resolve_windowed_r0_dispatch(WINDOWED_R0_UNIVERSAL_MASK | mask),
                Err(WindowLoweringError::UndefinedShapeBits { .. })
            ));
        }
    }

    #[test]
    fn cpu_committed_generated_artifacts_are_current() {
        let root = repo_root();
        let artifacts = windowed_r0_generated_artifacts().unwrap();
        assert_eq!(artifacts.len(), WINDOWED_R0_KERNEL_COUNT + 2);
        for (relative, rendered) in artifacts {
            let path = root.join(&relative);
            let committed = std::fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("{relative}: {error}"));
            assert_eq!(
                committed, rendered,
                "{relative} is stale; rerun generate_windowed_r0_production --write"
            );
        }
    }
}
