// Generated by gpu_memory_sweep. Regenerate after memory-relevant changes.
use crate::proof::memory_policy::{
    GkrMemoryPolicy, OpeningStrategy, ProofMemoryPolicy, WitnessCommitmentStrategy,
    WitnessMemoryPolicy, WitnessOpeningStrategy, WitnessPostCommitStorage,
};
use gpu_trace::witness::circuit_type::{
    CircuitType, DelegationCircuitType, UnrolledCircuitType, UnrolledMemoryCircuitType,
    UnrolledNonMemoryCircuitType,
};
pub(crate) const PRESET_ARENA_BYTES: &[usize] = &[22548578304, 32212254720];
pub(crate) const fn policy(circuit: CircuitType, arena_bytes: usize) -> ProofMemoryPolicy {
    match arena_bytes {
        22548578304 => match circuit {
            CircuitType::Delegation(DelegationCircuitType::BigIntWithControl) => {
                ProofMemoryPolicy {
                    gkr: GkrMemoryPolicy::Recompute {
                        value_layers: 1,
                        cache_layers: 2,
                    },
                    setup: OpeningStrategy::AllCosets,
                    memory: OpeningStrategy::AllCosets,
                    witness: WitnessMemoryPolicy {
                        commitment: WitnessCommitmentStrategy::AllCosets,
                        post_commitment: WitnessPostCommitStorage::RawEvaluations,
                        opening: WitnessOpeningStrategy::Recompute(OpeningStrategy::AllCosets),
                    },
                }
            }
            CircuitType::Delegation(DelegationCircuitType::Blake2GFunction)
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::MulDivUnsigned,
            )) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Materialize,
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawAndCosets,
                    opening: WitnessOpeningStrategy::ReuseCosets,
                },
            },
            CircuitType::Unrolled(UnrolledCircuitType::InitsAndTeardowns) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Materialize,
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawEvaluations,
                    opening: WitnessOpeningStrategy::Recompute(OpeningStrategy::AllCosets),
                },
            },
            CircuitType::Unrolled(UnrolledCircuitType::Memory(
                UnrolledMemoryCircuitType::LoadStoreWordOnly,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::AddSubLuiAuipcMop,
            )) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Recompute {
                    value_layers: 0,
                    cache_layers: 1,
                },
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawAndCosets,
                    opening: WitnessOpeningStrategy::ReuseCosets,
                },
            },
            CircuitType::Unrolled(UnrolledCircuitType::Memory(
                UnrolledMemoryCircuitType::LoadStoreSubwordOnly,
            )) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Recompute {
                    value_layers: 0,
                    cache_layers: 1,
                },
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawEvaluations,
                    opening: WitnessOpeningStrategy::Recompute(OpeningStrategy::AllCosets),
                },
            },
            CircuitType::Unrolled(UnrolledCircuitType::Unified) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Recompute {
                    value_layers: 0,
                    cache_layers: 2,
                },
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawAndCosets,
                    opening: WitnessOpeningStrategy::ReuseCosets,
                },
            },
            CircuitType::Delegation(DelegationCircuitType::Blake2WithCompression)
            | CircuitType::Delegation(DelegationCircuitType::KeccakSpecial5)
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::JumpBranchSlt,
            )) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Recompute {
                    value_layers: 1,
                    cache_layers: 1,
                },
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawAndCosets,
                    opening: WitnessOpeningStrategy::ReuseCosets,
                },
            },
            CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::ShiftBinary,
            )) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Recompute {
                    value_layers: 1,
                    cache_layers: 3,
                },
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawAndCosets,
                    opening: WitnessOpeningStrategy::ReuseCosets,
                },
            },
        },
        32212254720 => match circuit {
            CircuitType::Delegation(DelegationCircuitType::BigIntWithControl) => {
                ProofMemoryPolicy {
                    gkr: GkrMemoryPolicy::Recompute {
                        value_layers: 1,
                        cache_layers: 1,
                    },
                    setup: OpeningStrategy::AllCosets,
                    memory: OpeningStrategy::AllCosets,
                    witness: WitnessMemoryPolicy {
                        commitment: WitnessCommitmentStrategy::AllCosets,
                        post_commitment: WitnessPostCommitStorage::RawAndCosets,
                        opening: WitnessOpeningStrategy::ReuseCosets,
                    },
                }
            }
            CircuitType::Delegation(DelegationCircuitType::Blake2WithCompression)
            | CircuitType::Delegation(DelegationCircuitType::Blake2GFunction)
            | CircuitType::Delegation(DelegationCircuitType::KeccakSpecial5)
            | CircuitType::Unrolled(UnrolledCircuitType::Memory(
                UnrolledMemoryCircuitType::LoadStoreSubwordOnly,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::Memory(
                UnrolledMemoryCircuitType::LoadStoreWordOnly,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::AddSubLuiAuipcMop,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::JumpBranchSlt,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::MulDivUnsigned,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
                UnrolledNonMemoryCircuitType::ShiftBinary,
            ))
            | CircuitType::Unrolled(UnrolledCircuitType::Unified) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Materialize,
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawAndCosets,
                    opening: WitnessOpeningStrategy::ReuseCosets,
                },
            },
            CircuitType::Unrolled(UnrolledCircuitType::InitsAndTeardowns) => ProofMemoryPolicy {
                gkr: GkrMemoryPolicy::Materialize,
                setup: OpeningStrategy::AllCosets,
                memory: OpeningStrategy::AllCosets,
                witness: WitnessMemoryPolicy {
                    commitment: WitnessCommitmentStrategy::AllCosets,
                    post_commitment: WitnessPostCommitStorage::RawEvaluations,
                    opening: WitnessOpeningStrategy::Recompute(OpeningStrategy::AllCosets),
                },
            },
        },
        _ => panic!("unsupported memory preset arena"),
    }
}
