[package]
name = "gpu_native_build"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cmake = "0.1"
era_cudart_sys = "=0.156.0"
