//! Census model: what the next verifier run *consists of*, in the same affine
//! form as the cycle model — per-circuit-family cycle counts and delegation
//! call counts, each `c0 + Σ n_c · v_c` over the verified proof's counts.
//!
//! Family-cycle dims divide by the family's trace capacity to give the next
//! rung's instance census; delegation-call dims give the delegation circuits'
//! row demand. Inits/teardowns needs no dim: an unrolled rung always carries
//! exactly one i&t instance (its 16 sets span all of RAM), and unified layers
//! carry i&t inline.
//!
//! Calibrated by `tests/cost_model_trace.rs` (`emit_census_tables`) from the
//! same fixtures and region trace as the cycle table, with the same acceptance
//! gate shape (`census_estimate_matches_measurement_on_every_fixture`).

use super::{proof_counts, CircuitId, EstimateError};
use crate::program_proof::ProgramProof;
use verifier_common::fsv_binaries::{BlakeMode, FsvProgram};

pub const NUM_CENSUS_DIMS: usize = 10;
pub const NUM_FAMILY_DIMS: usize = 6;
pub type CensusVec = [u64; NUM_CENSUS_DIMS];

/// Dimension key for each `CensusVec` slot: `Riscv(f)` slots hold cycles the
/// verifier executes in family `f`, `Delegation(csr)` slots hold calls it makes.
pub const CENSUS_DIMS: [CircuitId; NUM_CENSUS_DIMS] = [
    CircuitId::Riscv(common_constants::ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::SHIFT_BINARY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::MUL_DIV_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::LOAD_STORE_WORD_ONLY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::LOAD_STORE_SUBWORD_ONLY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Delegation(common_constants::BLAKE2S_DELEGATION_CSR_REGISTER),
    CircuitId::Delegation(common_constants::BIGINT_OPS_WITH_CONTROL_CSR_REGISTER),
    CircuitId::Delegation(common_constants::KECCAK_SPECIAL5_CSR_REGISTER),
    CircuitId::Delegation(common_constants::BLAKE2S_G_FUNCTION_DELEGATION_CSR_REGISTER),
];

pub struct CensusTable {
    pub c0: CensusVec,
    pub v: &'static [(CircuitId, CensusVec)],
}

impl CensusTable {
    fn lookup(&self, circuit: CircuitId) -> Result<&CensusVec, EstimateError> {
        self.v
            .iter()
            .find(|(c, _)| *c == circuit)
            .map(|(_, v)| v)
            .ok_or(EstimateError::UnpricedCircuit { circuit })
    }
}

#[must_use]
pub fn census_table_for(program: FsvProgram, mode: BlakeMode) -> Option<&'static CensusTable> {
    CENSUS_TABLES
        .iter()
        .find(|(p, m, _)| *p == program && *m == mode)
        .map(|(_, _, t)| t)
}

/// Estimated census of verifying `proof` with the given fsv binary, as
/// `(dimension, value)` pairs in `CENSUS_DIMS` order. Same domain caveat as
/// `estimate_verifier_cycles`: valid canonical proofs only.
pub fn estimate_verifier_census(
    proof: &ProgramProof,
    program: FsvProgram,
    mode: BlakeMode,
) -> Result<Vec<(CircuitId, u64)>, EstimateError> {
    let table =
        census_table_for(program, mode).ok_or(EstimateError::UnknownBinary { program, mode })?;
    let found = proof.inits_and_teardown_proofs.len();
    if found != 1 {
        return Err(EstimateError::UnexpectedInitsAndTeardowns { found });
    }
    let mut total = table.c0;
    for (circuit, n) in proof_counts(proof) {
        if n == 0 {
            continue;
        }
        let row = table.lookup(circuit)?;
        for (acc, v) in total.iter_mut().zip(row) {
            *acc += v * n as u64;
        }
    }
    Ok(CENSUS_DIMS.into_iter().zip(total).collect())
}

// Generated by `emit_census_tables` in tests/cost_model_trace.rs; regenerate
// alongside the cycle table whenever the fsv binaries change.
pub static CENSUS_TABLES: &[(FsvProgram, BlakeMode, CensusTable)] = &[
    (
        FsvProgram::UnrolledBaseLayer,
        BlakeMode::Compression,
        CensusTable {
            c0: [454009, 56003, 32149, 0, 287238, 0, 25746, 0, 0, 0],
            v: &[
                (
                    CircuitId::Riscv(1),
                    [522423, 59420, 36769, 0, 218194, 0, 43645, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(2),
                    [536122, 60337, 37061, 0, 226872, 0, 44555, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(3),
                    [543888, 61141, 37396, 0, 229454, 0, 44625, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(4),
                    [535569, 60406, 38577, 0, 225300, 0, 44170, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(16),
                    [514011, 58893, 37056, 0, 218622, 0, 43652, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(17),
                    [524806, 59571, 37260, 0, 222573, 0, 44121, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1991),
                    [1517337, 129358, 46803, 0, 635083, 0, 83475, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1994),
                    [811680, 74387, 41698, 0, 335707, 0, 51688, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1995),
                    [797932, 73985, 40196, 0, 328734, 0, 51170, 0, 0, 0],
                ),
            ],
        },
    ),
    (
        FsvProgram::UnrolledRecursionLayer,
        BlakeMode::Compression,
        CensusTable {
            c0: [451345, 55433, 31734, 0, 278849, 0, 25620, 0, 0, 0],
            v: &[
                (
                    CircuitId::Riscv(1),
                    [522423, 59420, 36769, 0, 218194, 0, 43645, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(2),
                    [536122, 60337, 37061, 0, 226872, 0, 44555, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(3),
                    [543888, 61141, 37396, 0, 229454, 0, 44625, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(16),
                    [514011, 58893, 37056, 0, 218622, 0, 43652, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1991),
                    [1517337, 129358, 46803, 0, 635083, 0, 83475, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1994),
                    [811680, 74387, 41698, 0, 335707, 0, 51688, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1995),
                    [797932, 73985, 40196, 0, 328734, 0, 51170, 0, 0, 0],
                ),
            ],
        },
    ),
];
