// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

// =============================================================================
// WHIR opening verifier (EVM skeleton) — AGGRESSIVE schedule variant
// =============================================================================
//
// Dedicated copy of whir.sol with parameters matching the prover's aggressive
// config (`generate_whir_input_for_evm_aggressive`): 8 witness + 1 setup poly of
// 2^26, first LDE 64 => base RS codeword 2^32, folds [1,4,5,5,5] (fold by 2 in
// round 0, then 16, then 32/32/32 => 2^6 = 64 final coeffs), every codeword pinned
// at 2^32, 5 rounds, 100-bit pessimistic security. Verifies
// `proth120_whir_calldata_agg2.hex`. Every checked relation is a real assert via
// sink2() (reverts on mismatch). NOTE: matches the UPDATED schedule; needs the proof
// regenerated by `gen_whir_agg.sh` to validate on-chain (nmono=64 memory relocated).
//
// Field: P = 7*2^120 + 1 (Proth120, ~123 bit), one uint128/element, mulmod. keccak256
// for transcript/Merkle/PoW. Mutable state in hand-placed memory "registers"
// (REG_*); heavy logic in shallow Yul fns so the memory-unsafe (non-spilling)
// assembly stays under the EVM stack limit.
//
// ---- Input state: single hashed commitment + calldata preimage --------------
// Instead of ~33 storage slots (seed, batching, opening value, opening point,
// roots), ONE storage slot holds keccak256(preimage). The proof supplies the
// preimage as its first bytes; the verifier hashes it once and checks it against
// the slot (sink). Trades ~33 cold SLOADs (~69k gas) for 1 SLOAD + 1 keccak.
// Preimage layout: [seed:32][batching:16][opening:16][z_initial:nz*16]
//                  [witness_cap : CAP*32][setup_cap : CAP*32]
//
// ---- Merkle caps ------------------------------------------------------------
// CAP_LOG2 = log2(cap size). Each commitment is a cap of 2^CAP_LOG2 hashes, so a
// Merkle path is CAP_LOG2 levels shorter. Caps shrink paths (saves
// total_paths*CAP_LOG2 sibling words) but grow every commitment to CAP*32 bytes.
//
// ---- Layout: 8 witness polys + 1 setup poly --------------------------------
// The witness oracle batches 8 columns into one Merkle tree, the setup oracle 1
// column into another; round 0 opens both (gamma-batched), later rounds fold the
// single intermediate oracle. VARIANT selects the message size:
//   4 = production: message 2^26, initial LDE 32 => RS codeword 2^31
//   5 = test:       message 2^8,  initial LDE 32 => RS codeword 2^13
// =============================================================================

contract WhirVerifierAgg2 {
    // Field: Proth120, P = 7*2^120 + 1 (~123 bit), one uint128/element, mulmod.
    uint256 constant P    = 0x7000000000000000000000000000001;
    uint256 constant MASK = 0xffffffffffffffffffffffffffffffff;
    uint256 constant HALF = 0x3800000000000000000000000000001;  // 2^-1 = (P+1)/2
    // GEN = evaluation-domain generator for the RS codeword (2^32 for this schedule),
    // GEN_INV = GEN^-1. GEN = domain_generator_for_size(2^32) over Proth120.
    uint256 constant GEN     = 0x048b6b79ba191bd30b0910e6758fbc8e;
    uint256 constant GEN_INV = 0x0521cd7f2760eb0d44309dc8a890b5c2;

    // Aggressive schedule: 5 rounds (message 2^26, base codeword 2^32,
    // folds [1,4,5,5,5] => 2^6 = 64 final coeffs). See the schedule switch below.
    uint256 constant NUM_ROUNDS = 5;
    // Must match the prover's `eval_leaves` cargo feature. 0 (default): intermediate
    // oracles commit multilinear-COEFFICIENT leaves -> fold with the plain monomial
    // tensor (fold_multilinear). 1 (eval_leaves): they commit raw EVALUATIONS -> fold
    // with the coset base-root (fold_coset), like the round-0 base oracle.
    uint256 constant EVAL_LEAVES = 0;
    // cap size knob: keep CAP == 2^CAP_LOG2 in sync (Yul needs literal constants).
    uint256 constant CAP_LOG2 = 3;
    uint256 constant CAP      = 8;

    // ── hand-placed memory ────────────────────────────────────────────────────
    uint256 constant SEED_PTR     = 128;
    uint256 constant Z_PTR        = 2048;
    // z holds up to nz elements at Z_PTR..Z_PTR+nz*32. Production nz=26 fills
    // 2048..2880, so ACC_PREF must live OUTSIDE that span (it previously sat at
    // 2816 == z[24] and got clobbered). Park it in the free gap between the POW
    // region (POW_PTR..POW_PTR+numpow*96; <=~7968 for 53 constraints) and GAMMA.
    uint256 constant ACC_PREF_PTR = 12544;
    uint256 constant POW_PTR      = 2880;
    uint256 constant GAMMA_PTR    = 12608;
    uint256 constant FOLD_CH_PTR  = 16256;
    uint256 constant HPO_PTR      = 16448;
    uint256 constant LEAF_PTR     = 18048;  // leaf hashing + preimage hashing scratch
    uint256 constant REG_CD       = 22400;
    uint256 constant REG_CLAIM    = 22432;
    uint256 constant REG_NUMPOW   = 22464;
    uint256 constant REG_ZIOFF    = 22496;
    uint256 constant REG_CC       = 22560;
    uint256 constant REG_CURDELIN = 22592;
    // FBUF holds the folding buffer (leaf/coset fold, up to vp=32 values) AND the
    // final z-fold over nmono=2^rfin values. MONO holds the final monomials. With
    // rfin=6 both need 64*32 = 2048 bytes, so they are parked ABOVE all other live
    // memory (DRAW_BUF ends ~30528) instead of the old 16992/22752 slots (which only
    // had room for 16 values and would collide with LEAF/cap regions at 64).
    uint256 constant FBUF_PTR     = 31744;  // 2048 B: folding buffer + final z-fold
    uint256 constant MONO_PTR     = 33792;  // 2048 B: final monomials (2^rfin, <=64)
    // cap regions (each holds up to CAP*32 bytes)
    uint256 constant BCAP0_PTR    = 23296;  // witness base-oracle cap
    uint256 constant BCAP1_PTR    = 24320;  // setup base-oracle cap
    uint256 constant QCAP_PTR     = 26368;  // current query cap (rounds >= 1)
    uint256 constant NCAP_PTR     = 27392;  // just-read intermediate cap
    // Per-round query drawing (matches prover `draw_query_bits`/`BitSource`):
    //   QIDX_BUF holds the drawn query indices (<= 50 * 32 bytes);
    //   DRAW_BUF holds the little-endian u32 words squeezed from the seed.
    uint256 constant QIDX_BUF_PTR = 28416;  // drawn query indices
    uint256 constant DRAW_BUF_PTR = 30016;  // squeezed LE u32 words (one per slot)

    fallback() external {
        assembly {
        // Every checked WHIR relation flows through here: revert unless equal.
        function sink2(a, b) { if iszero(eq(a, b)) { revert(0, 0) } }
        function draw1() -> r {
            let s := keccak256(SEED_PTR, 32)
            mstore(SEED_PTR, s)
            // top 128 bits reduced mod P (matches prover `from_u128_with_reduction`).
            // Reduction is required: unreduced values break `sub(P, x)` for x > P.
            r := mod(shr(128, s), P)
        }
        function powmod(base, e) -> res {
            res := 1
            base := mod(base, P)
            for {} e { e := shr(1, e) } {
                if and(e, 1) { res := mulmod(res, base, P) }
                base := mulmod(base, base, P)
            }
        }
        function exp_pow2(x, k) -> res {
            res := x
            for { let i := 0 } lt(i, k) { i := add(i, 1) } { res := mulmod(res, res, P) }
        }
        function verify_pow(cp, pow_bits) -> next_cd {
            let nonce := shr(192, calldataload(cp))
            mstore(add(SEED_PTR, 32), shl(192, nonce))
            let h := keccak256(SEED_PTR, 40)
            mstore(SEED_PTR, h)
            sink2(shr(sub(256, pow_bits), h), 0)
            next_cd := add(cp, 8)
        }
        // Draw `num_q` query indices exactly as the prover's `draw_query_bits`:
        // squeeze `padded` little-endian u32 words from the seed (8 words per
        // keccak block, re-hashing the seed before each block), DROP the first
        // word, then read `qib` bits per index LSB-first from the remaining
        // stream (BitSource + assemble_query_index). Indices land in QIDX_BUF.
        function draw_queries(num_q, qib) {
            let num_bits := mul(num_q, qib)
            // num_required_words = next_multiple_of(num_bits, 32) / 32
            let nrw := shr(5, and(add(num_bits, 31), not(31)))
            // padded = next_multiple_of(nrw + 1, 8)
            let padded := and(add(add(nrw, 1), 7), not(7))
            let wi := 0
            for {} lt(wi, padded) {} {
                let d := keccak256(SEED_PTR, 32)
                mstore(SEED_PTR, d)
                for { let j := 0 } and(lt(j, 8), lt(wi, padded)) { j := add(j, 1) } {
                    let b := mul(j, 4)
                    // little-endian u32 from digest bytes [b, b+4)
                    let w := or(
                        or(byte(b, d), shl(8, byte(add(b, 1), d))),
                        or(shl(16, byte(add(b, 2), d)), shl(24, byte(add(b, 3), d))))
                    mstore(add(DRAW_BUF_PTR, mul(wi, 32)), w)
                    wi := add(wi, 1)
                }
            }
            // skip the first squeezed word => start at global bit 32
            for { let qq := 0 } lt(qq, num_q) { qq := add(qq, 1) } {
                let base_bit := add(32, mul(qq, qib))
                let idx := 0
                for { let k := 0 } lt(k, qib) { k := add(k, 1) } {
                    let gb := add(base_bit, k)
                    let word := mload(add(DRAW_BUF_PTR, mul(shr(5, gb), 32)))
                    idx := or(idx, shl(k, and(shr(and(gb, 31), word), 1)))
                }
                mstore(add(QIDX_BUF_PTR, mul(qq, 32)), idx)
            }
        }
        function fold_accumulator(alpha, n, zi_off) {
            let one_minus_alpha := addmod(1, sub(P, alpha), P)
            let alpha_coeff := addmod(addmod(alpha, alpha, P), sub(P, 1), P)
            let zi := mload(add(Z_PTR, zi_off))
            let eqv := addmod(one_minus_alpha, mulmod(alpha_coeff, zi, P), P)
            mstore(ACC_PREF_PTR, mulmod(mload(ACC_PREF_PTR), eqv, P))
            for { let i := 0 } lt(i, n) { i := add(i, 1) } {
                let b := add(POW_PTR, mul(i, 96))
                let s := mload(b)
                eqv := addmod(one_minus_alpha, mulmod(alpha_coeff, s, P), P)
                mstore(add(b, 32), mulmod(mload(add(b, 32)), eqv, P))
                mstore(b, mulmod(s, s, P))
            }
        }
        // high_powers_offsets: bit-reversed powers of the order-2^fold generator's
        // inverse (matches prover `initial_high_powers_offsets`). set_generator =
        // domain_generator_for_size(2^fold) = GEN^(2^(codeword_log2 - fold)), and
        // qib = codeword_log2 - fold, so set_gen_inv = GEN_INV^(2^qib) = exp_pow2(GEN_INV, qib).
        // hp[i] = set_gen_inv^i, then the length-2^(fold-1) array is bit-reversed.
        function compute_hpo(fold, qib) {
            let logc := sub(fold, 1)         // log2(count)
            let count := shl(logc, 1)
            let sgi := exp_pow2(GEN_INV, qib) // order-2^fold generator inverse
            let pw := 1
            for { let i := 0 } lt(i, count) { i := add(i, 1) } {
                // bit-reverse i over logc bits -> store hp[i] = sgi^i at position bitrev(i)
                let ri := 0
                for { let k := 0 } lt(k, logc) { k := add(k, 1) } {
                    ri := or(ri, shl(sub(sub(logc, 1), k), and(shr(k, i), 1)))
                }
                mstore(add(HPO_PTR, mul(ri, 32)), pw)
                pw := mulmod(pw, sgi, P)
            }
        }
        function fold_coset(fold, base_root_inv) -> folded {
            let n := shl(fold, 1)
            let root_inv := base_root_inv
            for { let round := 0 } lt(round, fold) { round := add(round, 1) } {
                let half := shr(1, n)
                let ch := mload(add(FOLD_CH_PTR, mul(round, 32)))
                for { let i := 0 } lt(i, half) { i := add(i, 1) } {
                    let a := mload(add(FBUF_PTR, mul(mul(i, 2), 32)))
                    let b := mload(add(FBUF_PTR, mul(add(mul(i, 2), 1), 32)))
                    let t := mulmod(addmod(a, sub(P, b), P), ch, P)
                    let root := mulmod(root_inv, mload(add(HPO_PTR, mul(i, 32))), P)
                    t := mulmod(t, root, P)
                    t := addmod(addmod(t, a, P), b, P)
                    t := mulmod(t, HALF, P)
                    mstore(add(FBUF_PTR, mul(i, 32)), t)
                }
                root_inv := mulmod(root_inv, root_inv, P)
                n := half
            }
            folded := mload(FBUF_PTR)
        }
        // Plain multilinear fold (monomial tensor eval) with the fold challenges,
        // WITHOUT the coset base-root. Used for INTERMEDIATE/FINAL oracle leaves,
        // whose stored values fold as f = e0 + e1*ch per step (the prover's default
        // `eval_multilinear_with_monomial_tensor` path, no `evals_to_multilinear_coeffs`).
        function fold_multilinear(fold) -> folded {
            let n := shl(fold, 1)
            for { let round := 0 } lt(round, fold) { round := add(round, 1) } {
                let half := shr(1, n)
                let ch := mload(add(FOLD_CH_PTR, mul(round, 32)))
                for { let i := 0 } lt(i, half) { i := add(i, 1) } {
                    let a := mload(add(FBUF_PTR, mul(mul(i, 2), 32)))
                    let b := mload(add(FBUF_PTR, mul(add(mul(i, 2), 1), 32)))
                    mstore(add(FBUF_PTR, mul(i, 32)), addmod(a, mulmod(b, ch, P), P))
                }
                n := half
            }
            folded := mload(FBUF_PTR)
        }
        // Merkle path of `depth` levels (already cap-reduced), then match a cap
        // entry. depth = query_index_bits - CAP_LOG2.
        //
        // The prover splits the query index the same way and lays out tree leaves
        // as [ bitreverse(coset_index) | internal_index ]:
        //   coset_index    = the low `coset_bits` bits of `qidx`
        //   internal_index = the remaining high bits
        // so the internal-index bits occupy the low (leaf-side) positions of the
        // physical tree index and the bit-reversed coset bits occupy the high
        // (cap-side) positions. We therefore walk the path over internal-index
        // bits first (LSB-first), then over coset-index bits in bit-reversed order
        // (MSB-first). The first `depth` bits form the Merkle path; the remaining
        // top bits index the cap. Each level orders current/sibling by its bit:
        // keccak(current || sibling) for a left child, keccak(sibling || current)
        // for a right child.
        function merkle_path(leaf_hash, depth, cap_ptr, cp, qidx, coset_bits) -> next_cd {
            let qib := add(depth, CAP_LOG2)
            let internal_bits := sub(qib, coset_bits)
            let internal_index := shr(coset_bits, qidx)
            let coset_index := and(qidx, sub(shl(coset_bits, 1), 1))

            let h := leaf_hash
            let cap_index := 0
            for { let pos := 0 } lt(pos, qib) { pos := add(pos, 1) } {
                // Bit of the physical tree index at position `pos` (LSB == leaf side).
                let bit
                switch lt(pos, internal_bits)
                case 1 {
                    bit := and(shr(pos, internal_index), 1)
                }
                default {
                    // Bit-reversed coset bit: path position `internal_bits + j`
                    // reads coset bit `coset_bits - 1 - j`.
                    let j := sub(pos, internal_bits)
                    bit := and(shr(sub(sub(coset_bits, 1), j), coset_index), 1)
                }

                switch lt(pos, depth)
                case 1 {
                    let sibling := calldataload(cp)
                    cp := add(cp, 32)
                    switch bit
                    case 0 {
                        // current node is the left child
                        mstore(0, h)
                        mstore(32, sibling)
                    }
                    default {
                        // current node is the right child
                        mstore(0, sibling)
                        mstore(32, h)
                    }
                    h := keccak256(0, 64)
                }
                default {
                    // Bits above the path form the cap index.
                    cap_index := or(cap_index, shl(sub(pos, depth), bit))
                }
            }
            sink2(h, mload(add(cap_ptr, mul(cap_index, 32)))) // match h against cap[cap_index]
            next_cd := cp
        }
        function batch_oracle(cp, cols, goff, vp, depth, cap_ptr, qidx, cb) -> next_cd {
            let wpc := shr(1, vp)
            let li := 0
            for { let c := 0 } lt(c, cols) { c := add(c, 1) } {
                let gamma := mload(add(GAMMA_PTR, mul(add(goff, c), 32)))
                for { let wj := 0 } lt(wj, wpc) { wj := add(wj, 1) } {
                    let w := calldataload(cp)
                    cp := add(cp, 32)
                    mstore(add(LEAF_PTR, mul(li, 32)), w)
                    li := add(li, 1)
                    let s0 := add(FBUF_PTR, mul(mul(wj, 2), 32))
                    let s1 := add(FBUF_PTR, mul(add(mul(wj, 2), 1), 32))
                    mstore(s0, addmod(mload(s0), mulmod(gamma, shr(128, w), P), P))
                    mstore(s1, addmod(mload(s1), mulmod(gamma, and(w, MASK), P), P))
                }
            }
            next_cd := merkle_path(keccak256(LEAF_PTR, mul(li, 32)), depth, cap_ptr, cp, qidx, cb)
        }
        function read_leaf(cp, vp, depth, cap_ptr, qidx, cb) -> next_cd {
            let words := shr(1, vp)
            for { let i := 0 } lt(i, words) { i := add(i, 1) } {
                let w := calldataload(cp)
                mstore(add(LEAF_PTR, mul(i, 32)), w)
                mstore(add(FBUF_PTR, mul(mul(i, 2), 32)), shr(128, w))
                mstore(add(FBUF_PTR, mul(add(mul(i, 2), 1), 32)), and(w, MASK))
                cp := add(cp, 32)
            }
            next_cd := merkle_path(keccak256(LEAF_PTR, mul(words, 32)), depth, cap_ptr, cp, qidx, cb)
        }
        // Reinterpret a 32-byte digest (8 big-endian u32 words) as the same 8
        // words each in little-endian byte order, keeping word positions. This
        // matches the prover's `commit_u32` cap absorption (LE u32 word bytes)
        // while the raw BE digest is still used for Merkle-root comparison.
        function bswap_digest(d) -> s {
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                let sh := sub(224, mul(i, 32))
                let w := and(shr(sh, d), 0xffffffff)
                let sw := or(
                    or(shl(24, and(w, 0xff)), shl(8, and(w, 0xff00))),
                    or(and(shr(8, w), 0xff00), and(shr(24, w), 0xff)))
                s := or(s, shl(sh, sw))
            }
        }
        function push_pow(current_scalar, coefficient) {
            let n := mload(REG_NUMPOW)
            let b := add(POW_PTR, mul(n, 96))
            mstore(b, current_scalar)
            mstore(add(b, 32), 1)
            mstore(add(b, 64), coefficient)
            mstore(REG_NUMPOW, add(n, 1))
        }
        function copy_cap(dst, src) {
            for { let i := 0 } lt(i, CAP) { i := add(i, 1) } {
                mstore(add(dst, mul(i, 32)), mload(add(src, mul(i, 32))))
            }
        }

        function do_query(r, fold, qib, vp, idx_mask, delin, cb, qq) {
            let cp := mload(REG_CD)
            let cur := mulmod(mload(REG_CURDELIN), delin, P)
            mstore(REG_CURDELIN, cur)
            let qidx := and(mload(add(QIDX_BUF_PTR, mul(qq, 32))), idx_mask)
            let base_root_inv := powmod(GEN_INV, qidx)
            let depth := sub(qib, CAP_LOG2)

            switch r
            case 0 {
                // Round 0 queries the base oracles: 8 witness columns (BCAP0) then
                // 1 setup column (BCAP1), gamma-batched into the folding buffer.
                for { let j := 0 } lt(j, vp) { j := add(j, 1) } { mstore(add(FBUF_PTR, mul(j, 32)), 0) }
                cp := batch_oracle(cp, 8, 0, vp, depth, BCAP0_PTR, qidx, cb)
                cp := batch_oracle(cp, 1, 8, vp, depth, BCAP1_PTR, qidx, cb)
            }
            default {
                cp := read_leaf(cp, vp, depth, QCAP_PTR, qidx, cb)
            }
            mstore(REG_CD, cp)
            // round 0 queries a base oracle (coset fold); later rounds query
            // intermediate oracles (plain multilinear fold, no base-root).
            let folded
            // round 0 (base oracle) always folds evals with the coset base-root;
            // intermediate rounds fold coeff leaves (fold_multilinear) unless the
            // prover used eval_leaves, in which case they too are raw evals.
            switch or(iszero(r), EVAL_LEAVES)
            case 1 { folded := fold_coset(fold, base_root_inv) }
            default { folded := fold_multilinear(fold) }
            push_pow(exp_pow2(powmod(GEN, qidx), fold), cur)
            mstore(REG_CC, addmod(mload(REG_CC), mulmod(folded, cur, P), P))
        }

        function do_internal(r, fold, q, pow_bits, qib, vp, idx_mask, cb) {
            let cp := mload(REG_CD)
            // read + absorb the next oracle's CAP (CAP*32 bytes)
            // keep BE digests for Merkle roots; absorb LE-word copies (commit_u32)
            for { let i := 0 } lt(i, CAP) { i := add(i, 1) } {
                let d := calldataload(add(cp, mul(i, 32)))
                mstore(add(NCAP_PTR, mul(i, 32)), d)
                mstore(add(SEED_PTR, add(32, mul(i, 32))), bswap_digest(d))
            }
            mstore(SEED_PTR, keccak256(SEED_PTR, add(32, mul(CAP, 32))))
            cp := add(cp, mul(CAP, 32))
            let ood_point := draw1()
            let ood_value := shr(128, calldataload(cp))
            calldatacopy(add(SEED_PTR, 32), cp, 16)
            mstore(SEED_PTR, keccak256(SEED_PTR, 48))
            cp := add(cp, 16)
            cp := verify_pow(cp, pow_bits)
            // prover order: PoW -> draw query bits -> draw delinearization
            draw_queries(q, qib)
            let delin := draw1()
            mstore(REG_CD, cp)
            push_pow(ood_point, delin)
            mstore(REG_CC, mulmod(ood_value, delin, P))
            mstore(REG_CURDELIN, delin)
            compute_hpo(fold, qib)
            for { let qq := 0 } lt(qq, q) { qq := add(qq, 1) } {
                do_query(r, fold, qib, vp, idx_mask, delin, cb, qq)
            }
            mstore(REG_CLAIM, addmod(mload(REG_CLAIM), mload(REG_CC), P))
            copy_cap(QCAP_PTR, NCAP_PTR) // this round's intermediate cap is next round's query cap
        }

        function do_final(fold, q, pow_bits, qib, vp, idx_mask, zi_off, rfin, cb) {
            let nmono := shl(rfin, 1)
            let cp := mload(REG_CD)
            calldatacopy(add(SEED_PTR, 32), cp, mul(nmono, 16))
            mstore(SEED_PTR, keccak256(SEED_PTR, add(32, mul(nmono, 16))))
            for { let wj := 0 } lt(wj, shr(1, nmono)) { wj := add(wj, 1) } {
                let w := calldataload(add(cp, mul(wj, 32)))
                mstore(add(MONO_PTR, mul(mul(wj, 2), 32)), shr(128, w))
                mstore(add(MONO_PTR, mul(add(mul(wj, 2), 1), 32)), and(w, MASK))
            }
            cp := add(cp, mul(nmono, 16))
            cp := verify_pow(cp, pow_bits)
            draw_queries(q, qib)
            compute_hpo(fold, qib)
            let depth := sub(qib, CAP_LOG2)

            for { let qq := 0 } lt(qq, q) { qq := add(qq, 1) } {
                let qidx := and(mload(add(QIDX_BUF_PTR, mul(qq, 32))), idx_mask)
                let base_root := powmod(GEN, qidx)
                cp := read_leaf(cp, vp, depth, QCAP_PTR, qidx, cb)
                // final round queries an intermediate oracle: coeff leaves fold with
                // the plain monomial tensor, unless eval_leaves (raw evals -> fold_coset).
                let folded
                switch EVAL_LEAVES
                case 1 { folded := fold_coset(fold, powmod(GEN_INV, qidx)) }
                default { folded := fold_multilinear(fold) }
                let qp := exp_pow2(base_root, fold)
                let ev := mload(add(MONO_PTR, mul(sub(nmono, 1), 32)))
                for { let j := sub(nmono, 1) } gt(j, 0) { j := sub(j, 1) } {
                    ev := addmod(mulmod(ev, qp, P), mload(add(MONO_PTR, mul(sub(j, 1), 32))), P)
                }
                sink2(ev, folded)
            }
            mstore(REG_CD, cp)

            for { let i := 0 } lt(i, nmono) { i := add(i, 1) } {
                mstore(add(FBUF_PTR, mul(i, 32)), mload(add(MONO_PTR, mul(i, 32))))
            }
            let active := nmono
            for { let level := 0 } lt(level, rfin) { level := add(level, 1) } {
                let half := shr(1, active)
                let zj := mload(add(Z_PTR, add(zi_off, mul(level, 32))))
                for { let i := 0 } lt(i, half) { i := add(i, 1) } {
                    let c0 := mload(add(FBUF_PTR, mul(mul(i, 2), 32)))
                    let c1 := mload(add(FBUF_PTR, mul(add(mul(i, 2), 1), 32)))
                    mstore(add(FBUF_PTR, mul(i, 32)), addmod(c0, mulmod(c1, zj, P), P))
                }
                active := half
            }
            let expected := mulmod(mload(ACC_PREF_PTR), mload(FBUF_PTR), P)
            let n := mload(REG_NUMPOW)
            for { let e := 0 } lt(e, n) { e := add(e, 1) } {
                let b := add(POW_PTR, mul(e, 96))
                let s := mload(b)
                let ev := mload(add(MONO_PTR, mul(sub(nmono, 1), 32)))
                for { let j := sub(nmono, 1) } gt(j, 0) { j := sub(j, 1) } {
                    ev := addmod(mulmod(ev, s, P), mload(add(MONO_PTR, mul(sub(j, 1), 32))), P)
                }
                ev := mulmod(ev, mload(add(b, 32)), P)
                ev := mulmod(ev, mload(add(b, 64)), P)
                expected := addmod(expected, ev, P)
            }
            sink2(expected, mload(REG_CLAIM))
        }

        // =================================================================== MAIN
        let start_gas := gas()

        // 8 witness + 1 setup poly -> 9 batched columns, 2 base caps (witness,setup).
        // Aggressive schedule: message 2^26, folds [1,4,5,5,5] => final poly 2^6 = 64
        // monomials (rfin 6).
        let nz := 26
        let gcount := 9
        let rfin := 6
        let nbcaps := 2

        // ---- parse + verify the single hashed state commitment -------------
        // preimage at calldata [0, plen): seed | batching | opening | z | base caps
        mstore(SEED_PTR, calldataload(0))
        let w1 := calldataload(32)
        let batching := shr(128, w1)
        mstore(REG_CLAIM, and(w1, MASK)) // opening value
        // z_initial (nz elems, packed 2/word; nz may be odd) at offset 64
        let zwords := shr(1, add(nz, 1)) // ceil(nz/2)
        for { let i := 0 } lt(i, zwords) { i := add(i, 1) } {
            let w := calldataload(add(64, mul(i, 32)))
            mstore(add(Z_PTR, mul(mul(i, 2), 32)), shr(128, w))
            mstore(add(Z_PTR, mul(add(mul(i, 2), 1), 32)), and(w, MASK))
        }
        // base caps: witness (BCAP0) then setup (BCAP1)
        let caps_off := add(64, mul(zwords, 32))
        calldatacopy(BCAP0_PTR, caps_off, mul(CAP, 32))
        calldatacopy(BCAP1_PTR, add(caps_off, mul(CAP, 32)), mul(CAP, 32))
        let plen := add(caps_off, mul(nbcaps, mul(CAP, 32)))
        // hash preimage, check vs the single stored commitment (sink)
        calldatacopy(LEAF_PTR, 0, plen)
        sink2(keccak256(LEAF_PTR, plen), sload(0))

        // gamma powers
        mstore(GAMMA_PTR, 1)
        {
            let g := 1
            for { let i := 1 } lt(i, gcount) { i := add(i, 1) } {
                g := mulmod(g, batching, P)
                mstore(add(GAMMA_PTR, mul(i, 32)), g)
            }
        }

        mstore(ACC_PREF_PTR, 1)
        mstore(REG_NUMPOW, 0)
        mstore(REG_ZIOFF, 0)
        mstore(REG_CD, plen) // proof stream starts after the preimage

        for { let r := 0 } lt(r, NUM_ROUNDS) { r := add(r, 1) } {
            // `cb` = coset bits = log2(LDE factor) for this round's oracle tree.
            let fold, q, pow_bits, qib, vp, cb
            // AGGRESSIVE PROTH120: 8 witness + 1 setup poly of 2^26, first LDE 64
            // => base RS codeword 2^32, every RS codeword pinned at 2^32 so the LDE
            // factor grows as the message folds: qib_r = 32 - fold_r, cb_r = log2(LDE_r).
            // Fold by 2 in round 0 only (keeps the 8-column base leaf small), then 16,
            // then aggressively by 32 => 2^6 = 64 final coeffs (rfin 6). 100-bit
            // pessimistic security, PoW <= 30 (computed by prover `config_from_folds`):
            //   folds=[1,4,5,5,5] cb=[6,7,11,16,21] q=[14,12,8,6,4] pow=[30,30,27,20,30]
            switch r
            case 0 { fold := 1 q := 14 pow_bits := 30 qib := 31 vp := 2  cb := 6 }
            case 1 { fold := 4 q := 12 pow_bits := 30 qib := 28 vp := 16 cb := 7 }
            case 2 { fold := 5 q := 8  pow_bits := 27 qib := 27 vp := 32 cb := 11 }
            case 3 { fold := 5 q := 6  pow_bits := 20 qib := 27 vp := 32 cb := 16 }
            default { fold := 5 q := 4 pow_bits := 30 qib := 27 vp := 32 cb := 21 }
            let idx_mask := sub(shl(qib, 1), 1)

            for { let s := 0 } lt(s, fold) { s := add(s, 1) } {
                let cp := mload(REG_CD)
                let w0 := calldataload(cp)
                let c0 := shr(128, w0)
                let c1 := and(w0, MASK)
                let c2 := shr(128, calldataload(add(cp, 32)))
                calldatacopy(add(SEED_PTR, 32), cp, 48)
                mstore(SEED_PTR, keccak256(SEED_PTR, 80))
                let alpha := draw1()
                mstore(REG_CD, add(cp, 48))
                let p1 := addmod(c0, addmod(c1, c2, P), P)
                sink2(addmod(c0, p1, P), mload(REG_CLAIM))
                mstore(REG_CLAIM,
                    addmod(mulmod(addmod(mulmod(c2, alpha, P), c1, P), alpha, P), c0, P))
                mstore(add(FOLD_CH_PTR, mul(s, 32)), alpha)
                let zi_off := mload(REG_ZIOFF)
                fold_accumulator(alpha, mload(REG_NUMPOW), zi_off)
                mstore(REG_ZIOFF, add(zi_off, 32))
            }

            switch lt(r, sub(NUM_ROUNDS, 1))
            case 1 { do_internal(r, fold, q, pow_bits, qib, vp, idx_mask, cb) }
            default { do_final(fold, q, pow_bits, qib, vp, idx_mask, mload(REG_ZIOFF), rfin, cb) }
        }

        // Every check passed (any failure would have reverted). Return the final
        // claim, the gas used, and the number of proof bytes consumed.
        let verify_gas := sub(start_gas, gas())
        mstore(0, mload(REG_CLAIM))
        mstore(32, verify_gas)
        mstore(64, mload(REG_CD))
        return(0, 96)
        }
    }
}

// Gas measurement is done directly against a deployed instance via a raw single
// transaction (anvil `cast send` of the proof as calldata), so no forge test
// harness (vm.readFile/parseBytes) is included here — that avoids the extra memory
// growth those cheatcodes add and yields the real single-tx gas.
