[package]
name = "zksync-airbender-circuit_common"
description = "The circuit_common crate of the zksync-airbender RISC-V zero-knowledge proving system."
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
field = { workspace = true }
fft = { workspace = true }
worker = { workspace = true }

[lib]
name = "circuit_common"
