// Per-circuit GKR forward-pass kernel wrapper for `add_sub_lui_auipc_mop`.
//
// Mirrors the witness-gen wrapper pattern: pull in the macro header, paste the
// generated layer body, emit the kernel. This file declares NO constants (those
// live once in gkr_forward_generation.cu) and contains no hand-written logic —
// the body is machine-generated by the `gpu_gkr_fwd_generator` crate.
#include "gkr_forward_generation.cuh"

namespace airbender::prover::gkr::forward::generation {

#include "generated/add_sub_lui_auipc_mop_layer0.cuh"

FWD_KERNEL(add_sub_lui_auipc_mop)

} // namespace airbender::prover::gkr::forward::generation
