// Per-circuit GKR forward-pass kernel wrapper for `blake2_with_extended_control`.
//
// Mirrors the add_sub wrapper: pull in the macro header, paste the generated
// layer body, emit the kernel. This file declares NO constants (those live once
// in gkr_forward_generation.cu) and contains no hand-written logic — the body is
// machine-generated by the `gpu_gkr_fwd_generator` crate. blake2 is a heavier,
// higher-fan-in delegation circuit (register/indirect memory tuples + vector
// lookups), exercising the codegen on a much larger layer-0 kernel.
#include "gkr_forward_generation.cuh"

namespace airbender::prover::gkr::forward::generation {

#include "generated/blake2_with_extended_control_layer0.cuh"

FWD_KERNEL(blake2_with_extended_control)

} // namespace airbender::prover::gkr::forward::generation
