// Generated by gpu_memory_sweep. Regenerate after memory-relevant changes.
use gpu_circuit_prover::proof::memory_policy::{
    FullWitnessWhirPolicy, OpeningPolicy, ProofMemoryPolicy, WitnessMemoryPolicy,
};
use gpu_trace::witness::circuit_type::{
    CircuitType, DelegationCircuitType, UnrolledCircuitType, UnrolledMemoryCircuitType,
    UnrolledNonMemoryCircuitType,
};
pub(crate) const ARENA_BYTES: usize = 32212254720;
pub(crate) const fn policy(circuit: CircuitType) -> ProofMemoryPolicy {
    match circuit {
        CircuitType::Delegation(DelegationCircuitType::BigIntWithControl)
        | CircuitType::Delegation(DelegationCircuitType::Blake2WithCompression)
        | CircuitType::Delegation(DelegationCircuitType::Blake2GFunction)
        | CircuitType::Delegation(DelegationCircuitType::KeccakSpecial5)
        | CircuitType::Unrolled(UnrolledCircuitType::InitsAndTeardowns)
        | CircuitType::Unrolled(UnrolledCircuitType::Memory(
            UnrolledMemoryCircuitType::LoadStoreSubwordOnly,
        ))
        | CircuitType::Unrolled(UnrolledCircuitType::Memory(
            UnrolledMemoryCircuitType::LoadStoreWordOnly,
        ))
        | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
            UnrolledNonMemoryCircuitType::AddSubLuiAuipcMop,
        ))
        | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
            UnrolledNonMemoryCircuitType::JumpBranchSlt,
        ))
        | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
            UnrolledNonMemoryCircuitType::MulDivUnsigned,
        ))
        | CircuitType::Unrolled(UnrolledCircuitType::NonMemory(
            UnrolledNonMemoryCircuitType::ShiftBinary,
        ))
        | CircuitType::Unrolled(UnrolledCircuitType::Unified) => ProofMemoryPolicy {
            setup: OpeningPolicy::FullMaterialization,
            memory: OpeningPolicy::FullMaterialization,
            witness: WitnessMemoryPolicy::FullMaterialization {
                whir: FullWitnessWhirPolicy::RetainCosets,
            },
        },
    }
}
