// @generated by generate_dr_windowed_r0_production; do not edit.

use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};

use super::binding::{DrWindowContinuationLaunchBinding, DrWindowLaunchBinding};

pub(crate) const DR_WINDOWED_R0_DEFINED_MASK: u32 = 0x1f;
pub(crate) const DR_WINDOWED_R0_BLOCK_THREADS: u32 = 288;

pub(crate) const DR_WINDOWED_CONT_DEFINED_MASK: u32 = 0x1f;
pub(crate) const DR_WINDOWED_CONT_BLOCK_THREADS: u32 = 288;

cuda_kernel_signature_arguments_and_function!(
pub(crate) GkrDrR0Window3,
desc: DrWindowLaunchBinding,
);

cuda_kernel_signature_arguments_and_function!(
pub(crate) GkrDrContinuationWindow3,
desc: DrWindowContinuationLaunchBinding,
);

pub(crate) struct DrWindowKernelEntry {
    pub symbol: GkrDrR0Window3Signature,
}

pub(crate) struct DrWindowContinuationKernelEntry {
    pub symbol: GkrDrContinuationWindow3Signature,
}

cuda_kernel_declaration!(
pub(crate) ab_gkr_dr_r0_window3_universal_kernel(desc: DrWindowLaunchBinding)
);

cuda_kernel_declaration!(
pub(crate) ab_gkr_dr_cont_window3_universal_kernel(desc: DrWindowContinuationLaunchBinding)
);

pub(crate) const DR_WINDOWED_R0_UNIVERSAL_KERNEL: DrWindowKernelEntry = DrWindowKernelEntry {
    symbol: ab_gkr_dr_r0_window3_universal_kernel,
};

pub(crate) const DR_WINDOWED_CONT_UNIVERSAL_KERNEL: DrWindowContinuationKernelEntry =
    DrWindowContinuationKernelEntry {
        symbol: ab_gkr_dr_cont_window3_universal_kernel,
    };
