//! Affine census of the next verifier run: per-family cycles and delegation
//! calls, `c0 + Σ n_c · v_c` over the proof's per-circuit counts. Family dims
//! partition total cycles. No i&t dim: always 1 on unrolled recursion layers,
//! inline on unified.
//!
//! Sec80 guests only. Regenerate via `emit_census_tables` when a guest
//! changes. blake2 g-function is unpriced → `UnpricedCircuit`.

use super::{proof_counts, CircuitId, EstimateError};
use crate::program_proof::ProgramProof;
use verifier_common::fsv_binaries::{BlakeMode, FsvProgram};

pub const NUM_CENSUS_DIMS: usize = 10;
pub const NUM_FAMILY_DIMS: usize = 6;
pub type CensusVec = [u64; NUM_CENSUS_DIMS];

/// `Riscv(f)` slots: cycles executed in family `f`. `Delegation(csr)` slots:
/// calls made.
pub const CENSUS_DIMS: [CircuitId; NUM_CENSUS_DIMS] = [
    CircuitId::Riscv(common_constants::ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::SHIFT_BINARY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::MUL_DIV_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::LOAD_STORE_WORD_ONLY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::LOAD_STORE_SUBWORD_ONLY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Delegation(common_constants::BLAKE2S_DELEGATION_CSR_REGISTER),
    CircuitId::Delegation(common_constants::BIGINT_OPS_WITH_CONTROL_CSR_REGISTER),
    CircuitId::Delegation(common_constants::KECCAK_SPECIAL5_CSR_REGISTER),
    CircuitId::Delegation(common_constants::BLAKE2S_G_FUNCTION_DELEGATION_CSR_REGISTER),
];

pub struct CensusTable {
    pub c0: CensusVec,
    pub v: &'static [(CircuitId, CensusVec)],
}

impl CensusTable {
    fn lookup(&self, circuit: CircuitId) -> Result<&CensusVec, EstimateError> {
        self.v
            .iter()
            .find(|(c, _)| *c == circuit)
            .map(|(_, v)| v)
            .ok_or(EstimateError::UnpricedCircuit { circuit })
    }
}

/// Census of verifying `proof`, as `(dim, value)` pairs in `CENSUS_DIMS`
/// order. Valid canonical proofs only.
pub fn estimate_verifier_census(
    proof: &ProgramProof,
    program: FsvProgram,
    mode: BlakeMode,
) -> Result<Vec<(CircuitId, u64)>, EstimateError> {
    Ok(CENSUS_DIMS
        .into_iter()
        .zip(census_totals(proof, program, mode)?)
        .collect())
}

pub(super) fn census_totals(
    proof: &ProgramProof,
    program: FsvProgram,
    mode: BlakeMode,
) -> Result<CensusVec, EstimateError> {
    let table = CENSUS_TABLES
        .iter()
        .find(|(p, m, _)| *p == program && *m == mode)
        .map(|(_, _, t)| t)
        .ok_or(EstimateError::UnknownBinary { program, mode })?;
    totals_from_counts(
        table,
        &proof_counts(proof),
        proof.inits_and_teardown_proofs.len(),
    )
}

fn totals_from_counts(
    table: &CensusTable,
    counts: &[(CircuitId, usize)],
    inits_and_teardowns: usize,
) -> Result<CensusVec, EstimateError> {
    if inits_and_teardowns != 1 {
        return Err(EstimateError::UnexpectedInitsAndTeardowns {
            found: inits_and_teardowns,
        });
    }
    let mut total = table.c0;
    for (circuit, n) in counts {
        if *n == 0 {
            continue;
        }
        let row = table.lookup(*circuit)?;
        for (acc, v) in total.iter_mut().zip(row) {
            *acc += v * *n as u64;
        }
    }
    Ok(total)
}

// Generated by `emit_census_tables`.
pub static CENSUS_TABLES: &[(FsvProgram, BlakeMode, CensusTable)] = &[
    (
        FsvProgram::UnrolledBaseLayer,
        BlakeMode::Compression,
        CensusTable {
            c0: [454009, 56003, 32149, 0, 287238, 0, 25746, 0, 0, 0],
            v: &[
                (
                    CircuitId::Riscv(1),
                    [522423, 59420, 36769, 0, 218194, 0, 43645, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(2),
                    [536122, 60337, 37061, 0, 226872, 0, 44555, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(3),
                    [543888, 61141, 37396, 0, 229454, 0, 44625, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(4),
                    [535569, 60406, 38577, 0, 225300, 0, 44170, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(16),
                    [514011, 58893, 37056, 0, 218622, 0, 43652, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(17),
                    [524806, 59571, 37260, 0, 222573, 0, 44121, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1991),
                    [1517337, 129358, 46803, 0, 635083, 0, 83475, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1994),
                    [811680, 74387, 41698, 0, 335707, 0, 51688, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1995),
                    [797932, 73985, 40196, 0, 328734, 0, 51170, 0, 0, 0],
                ),
            ],
        },
    ),
    (
        FsvProgram::UnrolledRecursionLayer,
        BlakeMode::Compression,
        CensusTable {
            c0: [451345, 55433, 31734, 0, 278849, 0, 25620, 0, 0, 0],
            v: &[
                (
                    CircuitId::Riscv(1),
                    [522423, 59420, 36769, 0, 218194, 0, 43645, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(2),
                    [536122, 60337, 37061, 0, 226872, 0, 44555, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(3),
                    [543888, 61141, 37396, 0, 229454, 0, 44625, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(16),
                    [514011, 58893, 37056, 0, 218622, 0, 43652, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1991),
                    [1517337, 129358, 46803, 0, 635083, 0, 83475, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1994),
                    [811680, 74387, 41698, 0, 335707, 0, 51688, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1995),
                    [797932, 73985, 40196, 0, 328734, 0, 51170, 0, 0, 0],
                ),
            ],
        },
    ),
];

#[cfg(test)]
mod tests {
    use super::*;
    use common_constants::{
        ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX, JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX,
        KECCAK_SPECIAL5_CSR_REGISTER,
    };

    const ADD_SUB: CircuitId = CircuitId::Riscv(ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX as u32);
    const JUMP_BR: CircuitId = CircuitId::Riscv(JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX as u32);
    const KECCAK: CircuitId = CircuitId::Delegation(KECCAK_SPECIAL5_CSR_REGISTER);

    const fn vec0(v: u64) -> CensusVec {
        let mut out = [0; NUM_CENSUS_DIMS];
        out[0] = v;
        out
    }

    const TEST_ROWS: [(CircuitId, CensusVec); 3] = [
        (ADD_SUB, vec0(10)),
        (JUMP_BR, vec0(100)),
        (KECCAK, vec0(1_000)),
    ];

    fn test_table() -> CensusTable {
        CensusTable {
            c0: vec0(1_000),
            v: &TEST_ROWS,
        }
    }

    fn total0(counts: &[(CircuitId, usize)], inits: usize) -> Result<u64, EstimateError> {
        totals_from_counts(&test_table(), counts, inits).map(|t| t[0])
    }

    #[test]
    fn sums_counts_times_per_proof_cost() {
        assert_eq!(total0(&[(ADD_SUB, 3), (JUMP_BR, 2)], 1).unwrap(), 1_230);
    }

    #[test]
    fn absent_circuits_contribute_nothing() {
        assert_eq!(total0(&[(ADD_SUB, 1)], 1).unwrap(), 1_010);
    }

    #[test]
    fn zero_count_is_treated_as_absent_not_unpriced() {
        assert_eq!(
            total0(&[(ADD_SUB, 1), (CircuitId::Delegation(9999), 0)], 1).unwrap(),
            1_010
        );
    }

    #[test]
    fn unpriced_circuit_is_a_hard_error() {
        assert!(matches!(
            total0(&[(CircuitId::Riscv(4242), 1)], 1),
            Err(EstimateError::UnpricedCircuit {
                circuit: CircuitId::Riscv(4242)
            })
        ));
    }

    #[test]
    fn inits_and_teardowns_must_be_exactly_one() {
        for found in [0usize, 2] {
            assert!(matches!(
                total0(&[(ADD_SUB, 1)], found),
                Err(EstimateError::UnexpectedInitsAndTeardowns { found: f }) if f == found
            ));
        }
    }

    #[test]
    fn delegation_and_riscv_keys_do_not_collide() {
        const ROWS: [(CircuitId, CensusVec); 2] = [
            (CircuitId::Riscv(7), vec0(5)),
            (CircuitId::Delegation(7), vec0(50)),
        ];
        let table = CensusTable {
            c0: vec0(0),
            v: &ROWS,
        };
        let counts = [(CircuitId::Riscv(7), 1), (CircuitId::Delegation(7), 1)];
        assert_eq!(totals_from_counts(&table, &counts, 1).unwrap()[0], 55);
    }
}
