//! Affine census of the next verifier run: per-family cycles and delegation
//! calls, `c0 + Σ n_c · v_c` over the proof's per-circuit counts. Family dims
//! partition total cycles. Standalone i&t is priced per proof; its verification
//! work contributes to the same family and delegation dimensions.
//!
//! The committed table is calibrated for the Sec100 Compression verifier
//! programs. Regenerate it locally via `emit_census_tables` when a guest
//! changes; see that test for fixture generation. blake2 g-function is
//! unpriced → `UnpricedCircuit`.
//!
//! `CENSUS_TABLES` is currently keyed by `(FsvProgram, BlakeMode)`, not
//! `SecurityLevel`, because every active `FsvProgram` resolves to the sole
//! Sec100 verifier set. Adding another security level requires extending the
//! estimator key and calibrating a separate table; Sec100 coefficients must not
//! be reused for it.

use super::{proof_counts, CircuitId, EstimateError};
use crate::program_proof::ProgramProof;
use verifier_common::fsv_binaries::{BlakeMode, FsvProgram};

pub const NUM_CENSUS_DIMS: usize = 10;
pub const NUM_FAMILY_DIMS: usize = 6;
pub type CensusVec = [u64; NUM_CENSUS_DIMS];

/// `Riscv(f)` slots: cycles executed in family `f`. `Delegation(csr)` slots:
/// calls made.
pub const CENSUS_DIMS: [CircuitId; NUM_CENSUS_DIMS] = [
    CircuitId::Riscv(common_constants::ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::SHIFT_BINARY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::MUL_DIV_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::LOAD_STORE_WORD_ONLY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Riscv(common_constants::LOAD_STORE_SUBWORD_ONLY_CIRCUIT_FAMILY_IDX as u32),
    CircuitId::Delegation(common_constants::BLAKE2S_DELEGATION_CSR_REGISTER),
    CircuitId::Delegation(common_constants::BIGINT_OPS_WITH_CONTROL_CSR_REGISTER),
    CircuitId::Delegation(common_constants::KECCAK_SPECIAL5_CSR_REGISTER),
    CircuitId::Delegation(common_constants::BLAKE2S_G_FUNCTION_DELEGATION_CSR_REGISTER),
];

pub struct CensusTable {
    pub c0: CensusVec,
    pub v: &'static [(CircuitId, CensusVec)],
}

impl CensusTable {
    fn lookup(&self, circuit: CircuitId) -> Result<&CensusVec, EstimateError> {
        self.v
            .iter()
            .find(|(c, _)| *c == circuit)
            .map(|(_, v)| v)
            .ok_or(EstimateError::UnpricedCircuit { circuit })
    }
}

/// Census of verifying `proof`, as `(dim, value)` pairs in `CENSUS_DIMS`
/// order. Valid canonical proofs only.
pub fn estimate_verifier_census(
    proof: &ProgramProof,
    program: FsvProgram,
    mode: BlakeMode,
) -> Result<Vec<(CircuitId, u64)>, EstimateError> {
    Ok(CENSUS_DIMS
        .into_iter()
        .zip(census_totals(proof, program, mode)?)
        .collect())
}

pub(super) fn census_totals(
    proof: &ProgramProof,
    program: FsvProgram,
    mode: BlakeMode,
) -> Result<CensusVec, EstimateError> {
    let table = CENSUS_TABLES
        .iter()
        .find(|(p, m, _)| *p == program && *m == mode)
        .map(|(_, _, t)| t)
        .ok_or(EstimateError::UnknownBinary { program, mode })?;
    totals_from_counts(
        table,
        &proof_counts(proof),
        proof.inits_and_teardown_proofs.len(),
    )
}

fn totals_from_counts(
    table: &CensusTable,
    counts: &[(CircuitId, usize)],
    inits_and_teardowns: usize,
) -> Result<CensusVec, EstimateError> {
    if inits_and_teardowns == 0 {
        return Err(EstimateError::UnexpectedInitsAndTeardowns {
            found: inits_and_teardowns,
        });
    }
    let mut total = table.c0;
    for (circuit, n) in counts {
        if *n == 0 {
            continue;
        }
        let row = table.lookup(*circuit)?;
        for (acc, v) in total.iter_mut().zip(row) {
            *acc += v * *n as u64;
        }
    }
    Ok(total)
}

// Generated by `emit_census_tables`.
pub static CENSUS_TABLES: &[(FsvProgram, BlakeMode, CensusTable)] = &[
    (
        FsvProgram::UnrolledBaseLayer,
        BlakeMode::Compression,
        CensusTable {
            c0: [23980, 6649, 1017, 0, 124233, 0, 455, 0, 0, 0],
            v: &[
                (
                    CircuitId::Riscv(1),
                    [645125, 78822, 49246, 0, 270723, 0, 58436, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(2),
                    [661102, 80015, 49582, 0, 280863, 0, 59710, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(3),
                    [672462, 80871, 49818, 0, 286330, 0, 59780, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(4),
                    [634214, 76509, 48254, 0, 269764, 0, 55811, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(16),
                    [633658, 78184, 49494, 0, 269839, 0, 58443, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(17),
                    [646324, 78841, 49736, 0, 275008, 0, 59094, 0, 0, 0],
                ),
                (
                    CircuitId::InitsAndTeardowns,
                    [510223, 63928, 40862, 0, 202563, 0, 29862, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1991),
                    [1965046, 169219, 58417, 0, 815218, 0, 113904, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1994),
                    [1020805, 97337, 53180, 0, 420113, 0, 69678, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1995),
                    [1023769, 97662, 52071, 0, 416709, 0, 69363, 0, 0, 0],
                ),
            ],
        },
    ),
    (
        FsvProgram::UnrolledRecursionLayer,
        BlakeMode::Compression,
        CensusTable {
            c0: [20994, 5477, 803, 0, 115938, 0, 350, 0, 0, 0],
            v: &[
                (
                    CircuitId::Riscv(1),
                    [645231, 78936, 49333, 0, 270725, 0, 58436, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(2),
                    [661391, 80349, 49737, 0, 280865, 0, 59710, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(3),
                    [672627, 81103, 49950, 0, 286332, 0, 59780, 0, 0, 0],
                ),
                (
                    CircuitId::Riscv(16),
                    [633620, 78117, 49367, 0, 269841, 0, 58443, 0, 0, 0],
                ),
                (
                    CircuitId::InitsAndTeardowns,
                    [510085, 63767, 40845, 0, 202563, 0, 29862, 0, 0, 0],
                ),
                (
                    CircuitId::Delegation(1991),
                    [1965114, 169313, 58496, 0, 815220, 0, 113904, 0, 0, 0],
                ),
            ],
        },
    ),
];

#[cfg(test)]
mod tests {
    use super::*;
    use common_constants::{
        ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX, JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX,
        KECCAK_SPECIAL5_CSR_REGISTER,
    };

    const ADD_SUB: CircuitId = CircuitId::Riscv(ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX as u32);
    const JUMP_BR: CircuitId = CircuitId::Riscv(JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX as u32);
    const KECCAK: CircuitId = CircuitId::Delegation(KECCAK_SPECIAL5_CSR_REGISTER);

    const fn vec0(v: u64) -> CensusVec {
        let mut out = [0; NUM_CENSUS_DIMS];
        out[0] = v;
        out
    }

    const TEST_ROWS: [(CircuitId, CensusVec); 4] = [
        (ADD_SUB, vec0(10)),
        (JUMP_BR, vec0(100)),
        (KECCAK, vec0(1_000)),
        (CircuitId::InitsAndTeardowns, vec0(200)),
    ];

    fn test_table() -> CensusTable {
        CensusTable {
            c0: vec0(800),
            v: &TEST_ROWS,
        }
    }

    fn total0(counts: &[(CircuitId, usize)], inits: usize) -> Result<u64, EstimateError> {
        let mut counts = counts.to_vec();
        counts.push((CircuitId::InitsAndTeardowns, inits));
        totals_from_counts(&test_table(), &counts, inits).map(|t| t[0])
    }

    #[test]
    fn sums_counts_times_per_proof_cost() {
        assert_eq!(total0(&[(ADD_SUB, 3), (JUMP_BR, 2)], 1).unwrap(), 1_230);
    }

    #[test]
    fn absent_circuits_contribute_nothing() {
        assert_eq!(total0(&[(ADD_SUB, 1)], 1).unwrap(), 1_010);
    }

    #[test]
    fn zero_count_is_treated_as_absent_not_unpriced() {
        assert_eq!(
            total0(&[(ADD_SUB, 1), (CircuitId::Delegation(9999), 0)], 1).unwrap(),
            1_010
        );
    }

    #[test]
    fn unpriced_circuit_is_a_hard_error() {
        assert!(matches!(
            total0(&[(CircuitId::Riscv(4242), 1)], 1),
            Err(EstimateError::UnpricedCircuit {
                circuit: CircuitId::Riscv(4242)
            })
        ));
    }

    #[test]
    fn inits_and_teardowns_counts_are_priced() {
        assert!(matches!(
            total0(&[(ADD_SUB, 1)], 0),
            Err(EstimateError::UnexpectedInitsAndTeardowns { found: 0 })
        ));
        assert_eq!(total0(&[(ADD_SUB, 1)], 2).unwrap(), 1_210);
        assert_eq!(total0(&[(ADD_SUB, 1)], 8).unwrap(), 2_410);
    }

    #[test]
    fn delegation_and_riscv_keys_do_not_collide() {
        const ROWS: [(CircuitId, CensusVec); 2] = [
            (CircuitId::Riscv(7), vec0(5)),
            (CircuitId::Delegation(7), vec0(50)),
        ];
        let table = CensusTable {
            c0: vec0(0),
            v: &ROWS,
        };
        let counts = [(CircuitId::Riscv(7), 1), (CircuitId::Delegation(7), 1)];
        assert_eq!(totals_from_counts(&table, &counts, 1).unwrap()[0], 55);
    }
}
