pub const ADD_SUB_LUI_AUIPC_MOP_FAMILY_INDEX: u8 = 1;
pub const ADD_SUB_LUI_AUIPC_MOP_FAMILY_NUM_FLAGS: usize = 8;

pub const JUMP_SLT_BRANCH_FAMILY_INDEX: u8 = 2;
pub const JUMP_SLT_BRANCH_FAMILY_NUM_BITS: usize = 5;

pub const SHIFT_BINARY_CSRRW_FAMILY_INDEX: u8 = 3;
pub const SHIFT_BINARY_CSRRW_FAMILY_NUM_FLAGS: usize = 6;

pub const WORD_ONLY_MEMORY_FAMILY_INDEX: u8 = 5;
pub const WORD_ONLY_MEMORY_FAMILY_NUM_FLAGS: usize = 1;

pub const SUBWORD_ONLY_MEMORY_FAMILY_INDEX: u8 = 6;
pub const SUBWORD_ONLY_MEMORY_FAMILY_NUM_FLAGS: usize = 1;

pub const MEMORY_FAMILY_INDEX: u8 = 6;
pub const MEMORY_FAMILY_NUM_FLAGS: usize = 1;
