// @generated by gpu_witness_eval_generator::regenerate_committed.
// Do not edit by hand.

use super::circuit_type::{
    CircuitType, DelegationCircuitType, UnrolledCircuitType, UnrolledMemoryCircuitType,
    UnrolledNonMemoryCircuitType,
};

#[rustfmt::skip]
pub(crate) fn expected_generated_witness_fingerprint(
    circuit_type: CircuitType,
) -> Option<[u32; 8]> {
    match circuit_type {
        CircuitType::Unrolled(UnrolledCircuitType::NonMemory(UnrolledNonMemoryCircuitType::AddSubLuiAuipcMop)) => Some([3537993250, 2011934060, 1786877081, 1918591032, 1851570675, 3068171226, 3990546829, 2461224730]),
        CircuitType::Delegation(DelegationCircuitType::BigIntWithControl) => Some([2529715145, 4035778132, 203525261, 2607397919, 1951507037, 3962226574, 1615386517, 3614671228]),
        CircuitType::Delegation(DelegationCircuitType::Blake2GFunction) => Some([4130508648, 3561528049, 598001293, 1007774573, 1703340311, 3229080524, 1373879237, 4235482289]),
        CircuitType::Delegation(DelegationCircuitType::Blake2WithCompression) => Some([3355076345, 3471701006, 2119526178, 2665029116, 3338308742, 621399653, 4082772299, 1454455459]),
        CircuitType::Unrolled(UnrolledCircuitType::NonMemory(UnrolledNonMemoryCircuitType::JumpBranchSlt)) => Some([3852795131, 2075171498, 4035306742, 2517513006, 766182683, 3904050387, 2466746710, 731133896]),
        CircuitType::Delegation(DelegationCircuitType::KeccakSpecial5) => Some([2091465232, 3520634083, 2149406436, 2595750038, 3570057967, 795069709, 810849063, 1482727057]),
        CircuitType::Unrolled(UnrolledCircuitType::Memory(UnrolledMemoryCircuitType::LoadStoreSubwordOnly)) => Some([2331193548, 4271390349, 845556435, 2457151592, 2567712434, 3032167865, 2808288420, 1288441120]),
        CircuitType::Unrolled(UnrolledCircuitType::Memory(UnrolledMemoryCircuitType::LoadStoreWordOnly)) => Some([3827563213, 3181901471, 441195764, 1045503572, 2454868275, 2821726825, 2789318589, 2090628853]),
        CircuitType::Unrolled(UnrolledCircuitType::NonMemory(UnrolledNonMemoryCircuitType::ShiftBinary)) => Some([3522952339, 3028439682, 1559768911, 4098586341, 1169901916, 3122398829, 1764773324, 2240878766]),
        CircuitType::Unrolled(UnrolledCircuitType::Unified) => Some([4186587711, 1060101313, 1105982690, 1159272747, 2496828968, 2576669586, 3371914282, 1722571917]),
        CircuitType::Unrolled(UnrolledCircuitType::NonMemory(UnrolledNonMemoryCircuitType::MulDivUnsigned)) => Some([2874997406, 4281888739, 3125301169, 3328740382, 3873912449, 238119334, 3369327276, 3521367031]),
        CircuitType::Unrolled(UnrolledCircuitType::InitsAndTeardowns) => None,
    }
}
