pub const OP_VERIFY_UNROLLED_RECURSION_LAYER_IN_UNIFIED_CIRCUIT: u32 = 1;
pub const OP_VERIFY_UNIFIED_RECURSION_LAYER_IN_UNIFIED_CIRCUIT: u32 = 2;

pub const OP_VERIFY_BASE_LAYER_IN_UNROLLED_CIRCUITS: u32 = 1;
pub const OP_VERIFY_RECURSIVE_LAYER_IN_UNROLLED_CIRCUITS: u32 = 2;

pub const DELEGATION_TYPES: &[u32; 6] = &[
    common_constants::BLAKE2S_DELEGATION_CSR_REGISTER,
    common_constants::BIGINT_OPS_WITH_CONTROL_CSR_REGISTER,
    common_constants::KECCAK_SPECIAL5_CSR_REGISTER,
    common_constants::KECCAK_THETA_RHO_CSR_REGISTER,
    common_constants::KECCAK_COLUMN_PARITY_CSR_REGISTER,
    common_constants::KECCAK_CHI5_CSR_REGISTER,
];
