[package]
name = "verifier_evm"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cs = { path = "../cs", features = ["compiler"] }
field = { path = "../field" }
prover = { path = "../prover" }
common_constants = { path = "../common_constants" }
transcript = { path = "../transcript" }
worker = { path = "../worker" }
serde_json = "1"
indoc = "2"

[dev-dependencies]
hex = "0.4"
