// @generated by generate_main_continuation_window_production; do not edit.

use era_cudart::{cuda_kernel_declaration, cuda_kernel_signature_arguments_and_function};

use super::binding::MainContinuationWindowLaunchBinding;

/// Universal executor for well-formed masks absent from the exact bank.
pub(crate) const MAIN_CONTINUATION_WINDOW_UNIVERSAL_MASK: u16 = 0x1f;

/// Threads per block for every generated continuation-window kernel.
pub(crate) const MAIN_CONTINUATION_WINDOW_BLOCK_THREADS: u32 = 96;

cuda_kernel_signature_arguments_and_function!(
    pub(crate) GkrBwdMainContinuationWindow3,
    desc: MainContinuationWindowLaunchBinding,
);

/// One generated continuation-window entry point.
pub(crate) struct MainContinuationWindowKernelEntry {
    pub mask: u16,
    pub publication_symbol: GkrBwdMainContinuationWindow3Signature,
    pub symbol: GkrBwdMainContinuationWindow3Signature,
    pub x01_symbol: GkrBwdMainContinuationWindow3Signature,
}

cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_00_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_00_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_00_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_01_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_01_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_01_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_03_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_03_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_03_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_07_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_07_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_07_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_13_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_13_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_13_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_17_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_17_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_17_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_1f_b4_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_1f_b4_publish_kernel(desc: MainContinuationWindowLaunchBinding)
);
cuda_kernel_declaration!(
    pub(crate) ab_gkr_bwd_main_cont_window3_shape_1f_b4_x01_kernel(desc: MainContinuationWindowLaunchBinding)
);

pub(crate) const MAIN_CONTINUATION_WINDOW_KERNELS: [MainContinuationWindowKernelEntry; 7] = [
    MainContinuationWindowKernelEntry {
        mask: 0x00,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_00_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_00_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_00_b4_x01_kernel,
    },
    MainContinuationWindowKernelEntry {
        mask: 0x01,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_01_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_01_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_01_b4_x01_kernel,
    },
    MainContinuationWindowKernelEntry {
        mask: 0x03,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_03_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_03_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_03_b4_x01_kernel,
    },
    MainContinuationWindowKernelEntry {
        mask: 0x07,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_07_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_07_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_07_b4_x01_kernel,
    },
    MainContinuationWindowKernelEntry {
        mask: 0x13,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_13_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_13_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_13_b4_x01_kernel,
    },
    MainContinuationWindowKernelEntry {
        mask: 0x17,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_17_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_17_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_17_b4_x01_kernel,
    },
    MainContinuationWindowKernelEntry {
        mask: 0x1f,
        publication_symbol: ab_gkr_bwd_main_cont_window3_shape_1f_b4_publish_kernel,
        symbol: ab_gkr_bwd_main_cont_window3_shape_1f_b4_kernel,
        x01_symbol: ab_gkr_bwd_main_cont_window3_shape_1f_b4_x01_kernel,
    },
];
