[package]
name = "verifier_common"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
field = { workspace = true }
blake2s_u32 = { workspace = true, default-features = false }
transcript = { workspace = true, default-features = false }
cs = { workspace = true, default-features = false }
prover = { workspace = true, default-features = false }
unroll = { workspace = true }
non_determinism_source = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }

serde_json = { version = "*", default-features = false, features = ["alloc"], optional = true }
quote = { version = "1", optional = true }
proc-macro2 = {version = "1", optional = true }
common_constants = { workspace = true, optional = true }

[dev-dependencies]
prover = { workspace = true, features = ["prover"] }
quote = { version = "1" }
proc-macro2 = {version = "1" }

[features]
no_inline = ["field/no_inline"]
security_80 = []
security_100 = []
worst_case_config_generation = []
blake2_with_compression = ["blake2s_u32/blake2_with_compression", "transcript/blake2_with_compression"]
blake2_g_function = ["blake2s_u32/blake2_g_function", "transcript/blake2_g_function"]
mop_extension = ["blake2s_u32/mop_extension", "transcript/mop_extension"]
special_opcodes_extension = ["blake2s_u32/special_opcodes_extension", "transcript/special_opcodes_extension"]
modular_ops = ["field/modular_ops"]
modular_fma = ["field/modular_fma"]
verifier_program = ["modular_ops"]
proof_utils = ["prover/prover", "dep:serde_json", "replace_csr", "dep:quote", "dep:proc-macro2"]
# If enabled, allows passing custom values into CSR.
replace_csr = ["prover/prover"]
# Use no-caches circuit descriptors (default for testing)
no_caches = []
# Instrument verifier to collect per-phase field-op / NDS-read / blake-hash counts
verifier_stats = [
    "dep:common_constants",
    "field/verifier_stats",
    "non_determinism_source/verifier_stats",
    "prover/verifier_stats",
    "blake2s_u32/verifier_stats",
    "common_constants/verifier_stats",
]

default = []
