[package]
name = "zksync-airbender-trace_holder"
description = "The trace_holder crate of the zksync-airbender RISC-V zero-knowledge proving system."
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
field.workspace = true
worker.workspace = true

[lib]
name = "trace_holder"
