[package]
name = "full_statement_verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
common_constants = { workspace = true }
verifier_common = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }

# setups = { workspace = true, default-features = false } // TODO: import as dependency if we make it no-std

[dev-dependencies]
serde_json = "*"
riscv_transpiler = { workspace = true }

[features]
verifiers = []

# This feature exists to only depend on the verifiers that are needed for
# `verify_unified_circuit_recursion_layer` function call. This way, we significantly
# reduce the dependency graph / artifact size, which might be important
# for certain use cases (e.g., WASM).
unified_verifier_only = []
unified_verifier_only_security_80 = []

security_80 = ["verifiers"]
security_100 = ["verifiers"]
blake2_with_compression = ["verifier_common/blake2_with_compression"]
modular_ops = ["verifier_common/modular_ops"]
verifier_program = ["modular_ops"]
replace_csr = ["verifier_common/replace_csr"]
proof_utils = ["verifier_common/proof_utils"]
default = ["security_80", "replace_csr", "verifiers", "proof_utils"]
# default = ["security_80"]
