[package]
name = "field"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde.workspace = true
rand = { workspace = true, default-features = false }
seq-macro = "0.3"
proc-macro2 = {version = "1", optional = true }
quote = {version = "1", optional = true }

[dev-dependencies]
proptest = "1"
criterion = "0.5"
rand = { workspace = true, features = ["std", "std_rng", "small_rng"] }

[[bench]]
name = "unreduced_accum"
harness = false

[features]
use_division = []
proc_macro_ops = ["proc-macro2", "quote"]
default = []
modular_ops = ["use_division"]
no_inline = []
