[package]
name = "field"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
common_constants = { workspace = true }
serde = { workspace = true }
rand = { workspace = true, default-features = false }
seq-macro = "0.3"
proc-macro2 = {version = "1", optional = true }
quote = {version = "1", optional = true }

[dev-dependencies]
proptest = "1"

[features]
proc_macro_ops = ["proc-macro2", "quote"]
default = []
modular_ops = []
modular_fma = ["modular_ops"]
no_inline = []
verifier_stats = []
