[package]
name = "pow_config_generator"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
quote = { version = "1" }
proc-macro2 = "1"

prover = { workspace = true, features = ["prover"] }
verifier_common = { workspace = true, features = ["proof_utils", "worst_case_config_generation"] }