[package]
name = "zksync-airbender-worker"
description = "The worker crate of the zksync-airbender RISC-V zero-knowledge proving system."
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rayon = "1"
num_cpus = "1"

[lib]
name = "worker"
