[package]
name = "gkr_eval_ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cs = { workspace = true, features = ["compiler"] }
field.workspace = true
serde.workspace = true

[dev-dependencies]
cs = { workspace = true, features = ["test-support"] }
serde_json = "1"
