name: "Rust CI"
on:
  push:
    branches:
      - main
      - stable
      - dev
  pull_request:

permissions: read-all

jobs:
  tests:
    name: tests
    runs-on: [matterlabs-ci-runner-highmem]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: |
          rustup set profile minimal
      - name: Compile
        run: cargo build --verbose
      # - name: tests
      #   run: cargo test --profile cli -- --nocapture

  transpiler_tests:
    name: transpiler tests
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: |
          rustup set profile minimal
      - name: Test
        env:
          RUST_MIN_STACK: 67108864
        run: |
          set -euo pipefail
          TESTS=(
            "jit::tests::test_few_instr"
            "jit::tests::test_jit_simple_fibonacci"
            "jit::tests::test_jit_recursive_verifier"
            "jit::tests::test_ensure_proof_correctness"
            "jit::tests::test_jit_full_block"
            "jit::tests::test_reference_block_exec"
            "jit::tests::run_and_compare"
            "replayer::test::test_replay_keccak_f1600"
            "vm::test::test_keccak_f1600"
            "vm::test::test_reference_block_exec"
            "vm::test::test_simple_fibonacci"
          )
          for test_name in "${TESTS[@]}"; do
            echo "Running ${test_name}"
            cargo test -p riscv_transpiler -- --nocapture --exact "${test_name}"
          done

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          rustflags: ""
      - name: Setup
        run: |
          rustup set profile minimal
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  simulator_isa_tests:
    name: ISA tests for simulator
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: |
          rustup set profile minimal
      - name: tests
        working-directory: ./risc_v_simulator
        run: cargo test --release --features=delegation

  full_recursion_fast:
    name: full_recursion_fast
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Display CPU Info
        run: |
          echo "Checking CPU capabilities..."
          lscpu | grep avx512 || echo "AVX-512 not supported on this runner"

      - name: Setup
        run: |
          rustup set profile minimal
      - name: Run Blake(fibonacci) and prove
        working-directory: execution_utils
        run: cargo test --release -- --nocapture --exact test_prove_fib
      - name: Run base layer recursive verifier over Blake(fibonacci) and prove
        working-directory: execution_utils
        run: cargo test --release -- --nocapture --exact test_prove_recursion_over_base
      - name: Run recursive layer verifier over base layer verifier and prove
        working-directory: execution_utils
        run: cargo test --release -- --nocapture --exact test_prove_recursion_over_recursion

  risc_v_test_delegations:
    name: risc_v_tests_delegations
    runs-on: [matterlabs-ci-runner]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: |
          rustup set profile minimal
      - name: Compile
        working-directory: ./risc_v_simulator
        run: cargo build --features delegation --verbose
      - name: test
        working-directory: ./risc_v_simulator
        run: cargo test --features delegation

  circuits_generated:
    name: circuits_generated
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: |
          rustup set profile default
      - name: Regenerate verifiers
        run: ./recreate_verifiers.sh
      - name: Check if anything has changed
        run: |
          MODIFIED_FILES=$(git status --porcelain)
          if [ -n "$MODIFIED_FILES" ]; then
            echo "The following files were modified - did you run ./recreate_verifiers.sh? "
            echo "$MODIFIED_FILES"
            exit 1
          else
            echo "No files were modified."
          fi

  build_verifier:
    runs-on: [matterlabs-ci-runner-c3d]
    name: build_verifier
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        working-directory: tools/verifier
        run: |
          rustup set profile minimal
          rustup target add riscv32i-unknown-none-elf
          cargo install cargo-binutils
          rustup component add llvm-tools-preview
          rustup component add rust-src
      - name: ObjCopy
        working-directory: tools/verifier
        run: cargo objcopy --release  -Z build-std=core,panic_abort,alloc -- -O binary app.bin
      - uses: actions/upload-artifact@v4
        with:
          name: verifier
          path: tools/verifier/app.bin

  build_cli_with_verify_80:
    name: build_cli_with_verify_80
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: rustup set profile minimal
      - name: Compile
        run: cargo build --release -p cli --no-default-features --features include_verifiers_80
      - uses: actions/upload-artifact@v4
        with:
          name: cli_with_verify_80
          path: |
            target/release/cli
            examples/basic_fibonacci/app.bin
            examples/basic_fibonacci/app.text

  build_cli_with_verify_100:
    name: build_cli_with_verify_100
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: rustup set profile minimal
      - name: Compile
        run: cargo build --release -p cli --no-default-features --features include_verifiers_100
      - uses: actions/upload-artifact@v4
        with:
          name: cli_with_verify_100
          path: |
            target/release/cli
            examples/basic_fibonacci/app.bin
            examples/basic_fibonacci/app.text

  build_cli_no_verifiers_80:
    name: build_cli_no_verifiers_80
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: rustup set profile minimal
      - name: Compile
        run: cargo build --release -p cli --no-default-features --features security_80

  build_cli_no_verifiers_100:
    name: build_cli_no_verifiers_100
    runs-on: [matterlabs-ci-runner-c3d]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Setup
        run: rustup set profile minimal
      - name: Compile
        run: cargo build --release -p cli --no-default-features --features security_100

  cli_smoke_80_base_verify:
    name: cli_smoke_80_base_verify
    runs-on: [matterlabs-ci-runner-c3d]
    needs: [build_cli_with_verify_80]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cli_with_verify_80
      - name: Setup
        run: |
          chmod +x ./target/release/cli
          mkdir -p output
      - name: Run
        run: ./target/release/cli run --bin examples/basic_fibonacci/app.bin --expected-results 144
      - name: Prove
        run: ./target/release/cli prove --bin examples/basic_fibonacci/app.bin --target base --backend cpu --cpu-cycles-bound 16777216 --cpu-worker-threads 8 --output-dir output --output-file proof.json
      - name: Verify
        run: ./target/release/cli verify --proof output/proof.json --bin examples/basic_fibonacci/app.bin

  cli_smoke_100_base_verify:
    name: cli_smoke_100_base_verify
    runs-on: [matterlabs-ci-runner-c3d]
    needs: [build_cli_with_verify_100]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cli_with_verify_100
      - name: Setup
        run: |
          chmod +x ./target/release/cli
          mkdir -p output
      - name: Run
        run: ./target/release/cli run --bin examples/basic_fibonacci/app.bin --expected-results 144
      - name: Prove
        run: ./target/release/cli prove --bin examples/basic_fibonacci/app.bin --target base --backend cpu --cpu-cycles-bound 16777216 --cpu-worker-threads 8 --output-dir output --output-file proof.json
      - name: Verify
        run: ./target/release/cli verify --proof output/proof.json --bin examples/basic_fibonacci/app.bin

  cli_smoke_80_recursion_unified_verify:
    name: cli_smoke_80_recursion_unified_verify
    runs-on: [matterlabs-ci-runner-c3d]
    needs: [build_cli_with_verify_80]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cli_with_verify_80
      - name: Setup
        run: |
          chmod +x ./target/release/cli
          mkdir -p output
      - name: Prove recursion unified
        run: ./target/release/cli prove --bin examples/basic_fibonacci/app.bin --target recursion-unified --backend cpu --output-dir output --output-file recursion_unified.json
      - name: Verify recursion unified
        run: ./target/release/cli verify --proof output/recursion_unified.json --bin examples/basic_fibonacci/app.bin

  cli_smoke_100_recursion_unified_verify:
    name: cli_smoke_100_recursion_unified_verify
    runs-on: [matterlabs-ci-runner-c3d]
    needs: [build_cli_with_verify_100]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cli_with_verify_100
      - name: Setup
        run: |
          chmod +x ./target/release/cli
          mkdir -p output
      - name: Prove recursion unified
        run: ./target/release/cli prove --bin examples/basic_fibonacci/app.bin --target recursion-unified --backend cpu --output-dir output --output-file recursion_unified.json
      - name: Verify recursion unified
        run: ./target/release/cli verify --proof output/recursion_unified.json --bin examples/basic_fibonacci/app.bin
